### ISSUE TITLE
Recipe oddity

### ISSUE THREAD

**Issue by ProxyPlayerHD** [GregTechCE/GregTech#1024]
Just why?

![2020-02-08_20-02-15](https://user-images.githubusercontent.com/13576843/74090643-0bbe3080-4aae-11ea-9f53-8c573d92ebca.gif)

Pretty sure there are more recipe types (beside plates) that do this for no reason...

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.2 (dev build on ee76c261078e4b7352893a2649e1ef71471cd6be)

**Enviroment:**
GTCE dev

**Outcome:**
Unable to reproduce bug not confirmed.

**Additional notes:**
This issue was probably caused by someone messing our recipes or it was already fixed. Either way this problem is not present in current version.

**Comment by ProxyPlayerHD** [comment]
i mean it was like half a year ago so it'd be weird if it wasn't fixed.
thanks though.

**Comment by SergeyScripter** [comment]
What?

вс, 28 июн. 2020 г., 20:42 ProxyPlayerHD <notifications@github.com>:
