### ISSUE TITLE
getItemStackDisplayName should not be @ ClientSide

### ISSUE THREAD

**Issue by omsfuk** [GregTechCE/GregTech#1054]
# Problem
in most cases, getItemStackDisplayName will not be invoked by server
but for the one probe, when try to detect items in container, it will invoke this method.
And this method was annotated to  @ClientSide, it will directly invoke Item::getItemStackDisplayName, which caused to wrong name

![Annotation 2020-04-02 154250](https://user-images.githubusercontent.com/26737684/78312001-f5e85b80-7584-11ea-8070-14c0c77893d2.png)
Actually it's sodium dust. All material(such like gear, rod, ingot) have wrong name **on dedicated server**. on client, it will display correct name "Sodium Dust".

# Solution
I have  removed all @ ClientSide on getItemStackDisplayName and replace I18n with TextComponentTranslation, it works well

**Comment by omsfuk** [comment]
Besides, TileEntitySurfaceRock::cacheModel cannot be annotated with ClientSide
The constructor TileEntitySurfaceRock() bytecode contains init invoke for cachedModel.
For a dedicated server, it cannot find field "cachedModel" and throw java.lang.NoSuchFieldError: cachedModel and crash

**Comment by omsfuk** [comment]
Finally, AdvancedTextWidget::wrapScreen also has problem, it will cause Multiblock Gui cannot open.

**Comment by Archengius** [comment]
Did you actually test ClientSideField? do you know it's content is not initialized on server?
getItemStackDisplayName will remain clientside, since translations should be always done on client and not on server, and i don't care if MC is stupid enough to invoke this method on server side to get these names here, since they won't be properly localized anyway, because server will always assume English.
And as of cachedModel, it is fixed by latest commit on master.
