### ISSUE TITLE
Invisible GUI for Multiblocks on server

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#1063]
Julien Marcon reports an error with the gui of multiblocks on servers in the master branch.

https://pastebin.com/3dS3db7x

(Not yet confirmed/reproduced)

**Comment by programgames** [comment]
### Expected Behavior
Open the gui of any multiblock on right click ( Black furnace for example)
### Current Behavior
Nothing is displayed
### Possible Solution
Uncomment the     @SideOnly(Side.CLIENT) annotation of the WrapScreen class (AdvancedTextWidget like 240)
### Steps to Reproduce
Run the client/server on the actual master branch and try to open a multiblock gui on a server.

**Comment by LAGIdiot** [comment]
Looking...
