### ISSUE TITLE
Surface Rock Materials missing

### ISSUE THREAD

**Issue by pyure** [GregTechCE/GregTech#1064]
https://pastebin.com/Wtke88Bx

Mostly reminder to self that these need addressing.

**Comment by LAGIdiot** [comment]
This was already fixed here #1049

**Comment by pyure** [comment]
I ran into the issue today while testing the master branch.

**Comment by LAGIdiot** [comment]
Yeah because you are using wrongly generated wordgen data from before my fix. You need to remove `config\gregtech\worldgen` folder from your game instance so it can re-deploy. This problem will not be present when upgrading from 1.9.0 as these files are not wrong yet. Down side is that new surface rocks will be generated only for veins that have it already registered.

**Comment by LAGIdiot** [comment]
Retested on version 1.9.2 (dev build on ee76c261078e4b7352893a2649e1ef71471cd6be) and works as expected. All of deployed wordgen files have correctly defined Surface Rocks.
