### ISSUE TITLE
Infinite steam in the bronze machines, if disconnect a BuildCraft fluid pipes

### ISSUE THREAD

**Issue by KenClaron** [GregTechCE/GregTech#108]
If fill a bronze machine with steam using BC fluid pipes, and then disconnect it from the BC fluid pipes, then the machine will be infinite(?) amount of steam. Exactly more 64 operations without steam.
![2018-06-11_10 10 49](https://user-images.githubusercontent.com/25456792/41220577-7b76d832-6d6a-11e8-99ad-016925ab2fcf.png)

Gregtech CE: 1.12.2-0.2.0.2
BuildCraft-transport: 1.12.2-7.99.17

**Comment by Archengius** [comment]
There is no issues with other fluid transport mods, like Thermal Dynamics. Seems like BC internal issue.

**Comment by EmosewaPixel** [comment]
And seeing that BC is still in alpha...

**Comment by AlexIIL** [comment]
I'm not sure how to duplicate this unfortunately - what should the steam extractor do when steam is inserted, and how can I test to see if it is receiving the expected amount of fluid?

**Comment by Archengius** [comment]
it has pretty small internal buffer for steam, it should progress recipes when it has enough steam
for every recipe cycle, you will see smoke on black side
you can take slime ball -> raw rubber dust recipe as example

**Comment by AlexIIL** [comment]
I can't reproduce this myself - I'm using a single tank, wooden fluid pipe, cobblestone fluid pipe, steam extractor, and hoppers to automate the process.

Whenever I add a single steam cell to the tank and move it through the BC fluid pipes and into the steam extractor it does exactly one operation.

If I split the fluid pipes (so that exactly half of the steam goes into the extractor, and half goes into a separate tank) then it *also* does exactly one operation. I didn't break and replace the extractor though, so that might be unrelated.

I've stepped through the buildcraft fluid insertion code, and the correct amount seems to end up in the extractor's fluid tank (less than 1000mB, but it looked like it was being drained by a few mB per tick near the end of the insertion).

If I break the BC fluid pipe at any point then it just stops inserting fluid, and won't process anything else after it finishes it's current operation. Can you provide more detailed steps for reproduction?

**Comment by Archengius** [comment]
guess that's up to issue author @KenClaron

**Comment by Archengius** [comment]
closed as inactive
