### ISSUE TITLE
[World] Can't find any diamond ore

### ISSUE THREAD

**Issue by WantaSanchez** [GregTechCE/GregTech#1107]
Hello. I read about this, but I can't find coar ore in stone. I disable generate vanilla ores in config for better experience, but now, I can't find diamonds (any ore). So, why this pretty mod not have a official wiki (wiki on github is so small...). Can any help my?

**Comment by LAGIdiot** [comment]
We probably can't directly help you to find ores in your world. But we could give you few pointers regarding how to find them. If you want you can jump to our Discord https://discord.gg/Tp3yDnE and ask there. Of curse if you are not able I will write some key points here later.

**Comment by LAGIdiot** [comment]
If you are using default worldgen provided with mod (not modified from outside) then Diamond Ore should spawn at **Overworld** between height **5** and **50**. It's vein should have **ellipsoid** shape with **13** diameter and should consist of **Diamond Ore (20%)**, Coal Ore (20%) and Graphite Ore (60%). On surface it may be indicated by **Black (Coal) Surface Rocks** like in picture bellow.

![Coal Surface Rocks](https://user-images.githubusercontent.com/3093101/84808918-a654f000-b009-11ea-90d0-8b633045c03f.png)

Beware that Coal vein is using same indication, so that Black (Coal) Surface Rocks does not automatically means diamonds.

In case that you are not using default worldgen, you can check worldgen files as defined on our Github Wiki and look for **ore:diamond**.

Good luck finding Diamonds!

**Comment by WantaSanchez** [comment]
Thanks for the advice, but I have never found carbon indicators on the surface, only for brown coal. At the same time, I have already visited a couple of thousand chunks. Maybe their generation depends on the biome? (I found many brown coal veins in the deserts)

**Comment by LAGIdiot** [comment]
In this case ore vain generation is not biome specific. It sounds quite strange that you did not find any Black (Coal) Surface Rocks even after visiting thousands chunks. Sure it does not have that high priority and chance for spawning Surface rock is 0-2 on chunk but we are talking about thousands of chunks here.

I suggest you to check game log if there are not errors regarding GTCE oregen (like parsing vein files). If there are please post them here. Also you can create copy of world and use mod like World Stripper to check if they are really not generated.

**Comment by WantaSanchez** [comment]
Interestingly, I created a new world for the test, but when I finally found a coal indicator on the surface, under us I found a vein ... Tin? Should this work like that? :)
[latest.log](https://github.com/GregTechCE/GregTech/files/4791575/latest.log)

**Comment by LAGIdiot** [comment]
I did not found anything regarding worldgen so there is nothing wrong with that.

Indicator on surface means that in that chunk there is at least 1 block from vein to which indicator belongs. Also no indicator does not mean that chunk has no ores in it.

So in this case it is absolutely okay to find Tin vein there.
