### ISSUE TITLE
Change all recipes that take 8/32/128/512/2048 EU/t

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#1121]
As the name says, those recipes will cause issues because of cable loss.

**Comment by idcppl** [comment]
Support, why have all this free area in between 1-32 if it's not going to be used. It also makes your base feel way more crammed into one spot.

**Comment by LAGIdiot** [comment]
Thank you for requesting this change.

I took a look at it and I decide to **decline it**.

As it maybe hard to work with recipes requiring EU from high end of tier range. It is also design challenge to make these builds work. Eliminating this would make GTCE easier which is not approach we would like to take at the moment. I am fully aware that we don't have enough recipes to cover full 1-2147483647 range and some areas may feel crammed mostly on LV and MV tier.

If you feel like some specific recipe should be moved down or up in required EU/t feel free to open new issue and we may look at that specific case.

**Comment by idcppl** [comment]
Making it 2 eu/t doesn't make it easier, makes it more convenient. Why should I build ugly bases that have all my machines stuck right up against a turbine? It still takes a full turbine in the long run.

**Comment by Shattered2909** [comment]
@LAGIdiot really!? That is silly... Can't you at least change it to 30/120/480? If I want to use Fluid Extractors properly I kinda have to use MV+ and disable Overclocking to not risk a loss. That is absolutely silly.

**Comment by pyure** [comment]
* "Risking" loss is misleading logic; GT power is about managing loss.  You don't "risk" it, you "incur" it and then you deal with it.
* LAGIdiot has already said you could submit specific machine recommendations for power reduction.  I'd personally be ok with reducing some common processes.
* @idcppl reducing it *does* make it easier once you factor in the power needs of your base rather than just logistics.  Cheaper processes = lower energy requirements.

Having said all of the above, I do find it unfortunate that early-game GT bases have a habit of fugly machine clumping and I'd be interested in exploring more ideas to attack that.

**Comment by Shattered2909** [comment]
Okay, fine, risk was the wrong term. My point is that absolutely requiring a generator right next to the Fluid Extractor is highly inconvenient and it is the only case where that's necessary. And as I said before, higher tier Fluid Extractors have that issue as well so the only option is to disable Overclocking.

**Comment by pyure** [comment]
Not strictly true.  The Fluid Extractor can requisition a second amp to fulfill its requirements.  
The following example works as expected:

`Buffer (2 Batteries) -> 2x Cable -> 2x Cable -> 2x Cable -> 2x Cable -> 2x Cable -> 2x Cable -> Fluid Extractor (Overclocking) `

Which again brings you back to the fact that there is loss here you need to manage.  Personally if I have 10 machines on a line, I tend to place the energy hogs closest to the buffer.

**Comment by idcppl** [comment]
I would never suggest batteries even to my worst enemies unless it is EV+.

**Comment by pyure** [comment]
That's strange.  I rush them because they make this whole situation so much easier to manage.  I have a better understanding now why you may be encountering so many difficulties.

**Comment by idcppl** [comment]
I don't have any difficulties, just annoyance of everything cramped into a corner. GTCE is a mod about net profitting. Batteries suggest against that. They require time and resources. If you're not profitting, you're waiting.

**Comment by pyure** [comment]
Time, resources and how you manage those are the primary GT-gate.  That's why many players consider it a "grindy" mod.  It may not be appropriate for your preferred play-style.
I've already described how buffers (which you've strangely described as a negative thing) can address many of your problems.  Now your options are to change your strategy, suggest some specific machines to reduce cost on, or play something else.

**Comment by idcppl** [comment]
????
You are way off the point that it laughable.

**Comment by pyure** [comment]
https://yourlogicalfallacyis.com/ad-hominem

**Comment by LAGIdiot** [comment]
I am locking this conversation as it is starting to be fruitless and more flame oriented.

As mentioned there are ways how to overcome this design challenge of recipes requiring upper bound of tier energy. Your options are:
- energy producer next to machine
- battery buffer next to machine
- using 2 AMPS of power to overcome lost
- using 1 AMP + battery in machine (only for occasional use)
- "down" transformer next to machine (if you are producing energy from hire tier)
- higher tier machine + disabling overclocking

I understand that some of them may not appeal to you, but these are options how to overcome this. Also not every recipe posses this challenge but only specific sets. If you really feel that some recipe really needs to be tweaked for energy requirements feel free to open new issue.
