### ISSUE TITLE
[Suggestion] Have Facades provide an amount based on input metal

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1184]
**Is your feature request related to a problem? Please describe.**
Currently, Facades can be crafted with Iron, Wrought Iron, and Aluminum plates, and each plate yields 4 facades. A suggestion would be to balance the amount of facades given based on the input metal.

**Describe the solution you'd like**
For example, Iron plates give 1 facade, Wrought Iron gives 2, and Aluminum gives 4, instead of all metals giving 4. Or changing the output amount to be slightly higher and balancing the output numbers around this new output amount.

**Comment by LAGIdiot** [comment]
Thank for requesting this change. I think it makes sense to that plate from material which requires more processing or higher level of processing should provide more. I would go for 2,3,5 facades respectively because there may be players which care for look from first stage and should have access to it in reasonable quantities.
