### ISSUE TITLE
[BUG] JEI's "R" and "U" not triggering from machines that uses fluids

### ISSUE THREAD

**Issue by PrototypeTrousers** [GregTechCE/GregTech#1234]
Pressing the JEI Recipes/Usage hotkeys on fluid inside gregtech machines dont show Recipes and Usages anymore

**Versions**
Forge: 14.23.5.2854
GTCE: gregtech-1.12.2-1.10.1.557
Mods: ONLY gregtechCE, JEI, codechickenlib

**Setup**
Playing Solo
New world generated

**Steps To Reproduce**
1)Placed down Chemical reactor
2)Placed bucket of water inside chemical reactor
3)Hovered mouse over water fluid on input slot
4)Pressed R and U
5)Nothing happens

**Expected behavior**
ON gregtech-1.12.2-1.8.13.465 JEI would pop-up with Recipes/Usages of said fluid
SINCE gregtech-1.12.2-1.9.0.481. Nothing happens

**Comment by LAGIdiot** [comment]
Thank you for reporting this issue. This may be related to update of JEI dependency. I will have look at it later.

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.0+

**Enviroment:**
Twitch Launcher

**Outcome:**
Bug confirmed

**Additional notes:**
This problem was introduced between 1.8.13 and 1.9.0. At same time quite few changes were introduced (https://github.com/GregTechCE/GregTech/compare/v1.8.13...v1.9.0). May best guess is that this problem is related to Widget system for GUI introduction. Further investigation needed.
