### ISSUE TITLE
[BUG] Incorrect Multi Smelter Preview

### ISSUE THREAD

**Issue by WesMaggs** [GregTechCE/GregTech#1262]
**Describe the bug**
The 'Multiblock Pattern' preview for the Multi Smelter shows a single MV Energy input hatch on the back center bottom layer.  If followed exactly this pattern will work for about 30s then 'break' to an "invalid structure" in the GUI.  The correct multiblock requires 2 energy inputs, much like the EBF.

**Versions**
Forge: 1.12.2-2.6.2.83
GTCE: 1.12.2-1.10.0.546
_Modpack: FTB Interactions via launcher v. 2.0.9

**Setup**
Multiplayer Server

**Steps To Reproduce**
See bug description

**Comment by LAGIdiot** [comment]
Thank you for creating this issue.

I think you made some mistakes in provided versions.
gtce2oc is not us but https://www.curseforge.com/minecraft/mc-mods/gtce2oc
For GTCE you can find version on file gregtech-1.12.2-XXX.jar

Was this also reported to FTB Interactions issue tracker? As it may be something caused by modifications done by modpack authors. Also what version of modpack you are using?

**Comment by WesMaggs** [comment]
Whoops.  Updated the post with the correct info.  I have not put it on the FTBI tracker, will do it now.

**Comment by LAGIdiot** [comment]
Thank you for updating description and creating issue on FTB side.

**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.2 (dev build on f49c3f6427eb9b02a4797c31aa16bbfa875a7d2f)

**Enviroment:**
GTCE dev

**Outcome:**
Unable to reproduce. Multiblock did not break to invalid structure after extensive usage.

**Additional info:**
There is nothing in code which points to more then one Energy Input requirement. Is it modpack specialty?
Waiting initial assessment of bug from modpack authors may provide more info.

**Comment by LAGIdiot** [comment]
I am closing this issue as stale. If there is still required any action from GTCE side then feel free to re-open this issue.
