### ISSUE TITLE
[BUG] server console spam of "Bad One probe Implem"

### ISSUE THREAD

**Issue by Zafaranec** [GregTechCE/GregTech#1283]
**Describe the bug**
I read the server log on second monitor and get spam of messages like: 
[Server thread/ERROR] [gregtech]: Bad One probe Implem: public class java.lang.IllegalArgumentException Parameter specified as non-null is null: method com.cout970.magneticraft.systems.tileentities.TileBase.getCapability, parameter capability com.cout970.magneticraft.systems.tileentities.TileBase

[Server thread/ERROR] [gregtech]: Bad One probe Implem: public class java.lang.NullPointerException null cassiokf.industrialrenewal.tileentity.TileEntityBulkConveyorHopper

first when I look at Magneticraft sifter, second when I look at Industrial Renewal BulkConveyor with hopper
I get Magneticraft and Mekanism messages from Gregicality but that is fixed, but now it say Gregtech problem, I don't know, which is that problem.

**Versions**
Forge: 14.23.5.2854
GTCE: 1.12.3.569
Modpack: https://www.curseforge.com/minecraft/modpacks/all_of_tech
**Setup**
Multiplayer

**Steps To Reproduce**
1) look at eg. Magneticraft sifter upper part or Crushing Table
2) in server console you can see this messages more than one, every second, until you turn from that

**Expected behavior**
Isn't that obvious?

**Comment by LAGIdiot** [comment]
Thank you for reporting this bug.

**Version:**
Modpack: All_of_Tech 2.2.0
Forge: 14.23.5.2854
GTCE: 1.10.3.569

**Enviroment:**
Twitch Launcher (newly downloaded modpack)

**Outcome:**
**Bug confirmed**, but it is **not on our side**. It is **caused by Gregicality** and it is log under GTCE because they are using our logger. We don't play any role in it as it does not happened without Gregicality installed.

**Additional notes:**
I will report this problem to them, link this issue to it and mention you in it.

**Comment by Zafaranec** [comment]
Thank you very, very much.
