### ISSUE TITLE
[BUG] Cannot put covers on the bottom of GTCE chests

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1312]
**Describe the bug**
Covers cannot go on the bottom of GTCE chests, despite being able to be put on the bottom of every other machine/storage block.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.5.582
_Modpack:_ None.
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Place a GTCE wooden chest down (but similar for all chests)
2) Attempt to attach a cover to the bottom of the chest (tested with conveyor and Robot Arm)
3) See that the cover does not attach to the bottom of the chest
4) Repeat the process with an Item Filter, and see that the filter is not attached as a cover

**Expected behavior**
For covers to be able to be attached to the bottom of chests, since they can be attached to the bottom of all other blocks and machines

**Comment by LAGIdiot** [comment]
Thank your for creating this issue. I investigated this case and you are right it is not possible to place cover on bottom side of chest. But it is design decision not a bug.

Now question is what will it bring us to change this design and allow placing cover on bottom as opposition to work required to do so. And with that I will leave this open for discussion.

**Comment by eutropius225** [comment]
I can't think of any advantages of this design decision. It's inconsistent with the behaviour of other blocks, and is just generally inconvenient. I would understand if it was the top side, but not the bottom side.

**Comment by Archengius** [comment]
It is consistent and logic behind it is very simple: covers take 1/16 of a block space for their host panels when they are installed on non-full blocks, and chests simply don't have that free space in front and on the bottom.

**Comment by eutropius225** [comment]
In that case ICoverable could be slightly altered so the cover plate isn't required when on the bottom. [This method](https://github.com/GregTechCE/GregTech/blob/22a594d9f945c2281a354e8de4aef84d94a895bd/src/main/java/gregtech/api/cover/ICoverable.java#L60) could have another parameter for side, and then, for consistency [this one](https://github.com/GregTechCE/GregTech/blob/22a594d9f945c2281a354e8de4aef84d94a895bd/src/main/java/gregtech/api/cover/ICoverable.java#L64) should also. In that way it would be possible to put covers on the bottom without requiring space for the cover plate.

**Comment by Archengius** [comment]
Which would actually make it... inconsistent between sides? Again, I don't see any issues with not being able to place covers on these sides, logically it makes a perfect sense from collision standpoint.

**Comment by eutropius225** [comment]
The inconsistency is that you can't place covers on the bottom of the chest. You say that's because there's no space for it, because it needs a cover plate, yet that's not an issue for full block machines.

**Comment by Archengius** [comment]
Because full block machines are actually.. full block and can support covers without needing any cover plates?

**Comment by eutropius225** [comment]
How is the bottom of a chest not full enough to support a cover, but too full to fit a cover plate on? What does a cover plate/machine side provide that a chest bottom does not? If it's really so important, why isn't it a tangible item I have to craft before attaching covers to chests?

**Comment by Archengius** [comment]
It is not a full block surface because it's physical size is 15/16 of a block, yet main chest box starts at height 0 and ends at 15/16, that's why you can place cover on top side and cannot place it on the bottom.
Again, looks perfectly fine to me.

**Comment by Exaxxion** [comment]
My two cents: this particular behavior of chests is a frequent point of confusion for our pack's playerbase, followed by disappointment when we clarify that they're not doing anything wrong, you just can't put a cover there. It works for everything else, then it inexplicably can't for the chest and they have to rethink their whole layout to work around it.

**Comment by ZetaZeroPrime** [comment]
> It is consistent and logic behind it is very simple: covers take 1/16 of a block space for their host panels when they are installed on non-full blocks,

How is this information relayed to the player?

I am allowed to place covers on full block machines, even between two full block machines.  Therefore I assumed covers don't take up any space.  There is no in-game information that contradicts this.  I don't even know what a host panel is.

If the design stays as is, can we get a console message to inform the player?  Something like "Covers are not allowed on this side".

**Comment by DStrand1** [comment]
I would like to bring the discussion on this issue back up, as I've had many people consistently talk about their dislike of covers not being able to be placed on chests. I and many others think this should be changed, but if this issue is rigid, and not willing to be changed, I think there should at the very least be a much clearer indication of the fact that covers cannot be placed on the bottom.

**Comment by smudgerox** [comment]
>Because full block machines are actually.. full block and can support covers without needing any cover plates?

Limiting creativity and flexibility in setups because of a completely arbitrary restriction based on how you think chests should behave is quite silly to me, Arch. It’s not the real world, it’s Minecraft. We have blocks floating in mid-air, there’s no need for a cover to be “supported” by anything.

I’m no programmer, but couldn’t you just not render the “cover plate” on the bottom side to avoid collision/z-fighting regarding the rendering part of this issue? Frankly, I wouldn’t mind the cover plate being done away with entirely and just have the cover render flush with the chest on the top and sides as it does right now with full blocks, would look cleaner. Or maybe have chests be full blocks? Not sure how that would look, though.

There just aren’t any functional downsides to allowing it, no matter what the solution ends up being. Covers being intuitive and consistent with player’s expectations is above all else, the way I see it.
