### ISSUE TITLE
[BUG] Phosphorus positive Crafting loop exists via Posphorus Pentoxide

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1318]
**Describe the bug**
A Phosphorus positive loop exists via making phosphorus pentoxide, allowing for infinite phosphorus to be generated with the addition of water and oxygen.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.5.582
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
The Recipe chain is:

1) 4 Phosphorus dust + 10B Oxygen in a Chemical Reactor -> 14 Phosphorus Pentoxide Dust
2) 1 Phosphorus Pentoxide dust + 6B water in a chemical reactor -> 4B Phosphoric Acid
3) 7B Phosphoric Acid in an Electrolyzer -> 4 Phosphorus dust and 3B Hydrogen.

This is a recipe loop, as you get much more Phosphorus via Phosphoric Acid then you put in.

**Expected behavior**
No recipe loop

**Additional context**
An easy solution would be to disable the decomposition of Phosphoric Acid, or remove the Phosphoric Acid from Phosphoric Pentoxide recipe in the chemical reactor.

**Comment by LAGIdiot** [comment]
Thanks for reporting this issue. I think that we can remove Phosphorous Pentoxide Dust + Water to Phosphoric Acid recipe for Chemical reactor. As it seems the most OP and easiest to remove. This should not create problem with obtaining any of interested materials or once related to them.

**Comment by Exaxxion** [comment]
Worth noting that Phosphorous Pentoxide can be obtained from ashes you get as byproducts of other processes. At the very least the decomposition recipe needs to be maintained or you'll end up with a bunch of an unusable item.

Phosphorous Pentoxide is a real way in which to obtain Phosphoric Acid through reaction with water. The issue is just that the recipes aren't implemented soundly.

4 Phosphorous and 10k mB Oxygen should produce 1mol (1k mB) of Phosphorous Pentoxide. Electrolysis should mirror this recipe.

The balanced equation for turning Phosphorous Pentoxide into Phosphoric Acid using Water is:
`P4O10 + 6(H2O) -> 4(H3PO4)`

As such a properly balanced recipe could be implemented such that:
1k mB of Phosphorous Pentoxide and 6k mB of Water produces 4k mB of Phosphoric acid.

**Comment by DStrand1** [comment]
So with regards to fixing this, it seems clear to me that the recipe stated in step 2 of the original issue statement should be the full stack of 14 phosphorus pentoxide, rather than just one. But while looking into the Phosphoric Acid electrolysis recipe, it doesnt really make any sense to me. `7(H3PO4) -> 4P + 3H`? Am I misunderstanding something, or does that recipe seem extremely wrong.

**Comment by Exaxxion** [comment]
I misspoke regarding P4O10 and yes 1 mol would indeed be 14 dusts rather than 1 bucket of fluid.

Electrolysis of phosphoric acid isn't particularly sensible given that it primarily decomposes into `H + H2PO4-`. I think it would make the most sense to just remove the electrolyzer recipe for it. If we're going with Videogame Logic and the electrolyzer is magic, one mole of H3PO4 should split into equivalent moles of its constituent elements: 3k mB Hydrogen, 1 Phosphorous dust, and 4k mB Oxygen.
