### ISSUE TITLE
[BUG] The turbine increases the speed without rotor

### ISSUE THREAD

**Issue by sidechko** [GregTechCE/GregTech#1367]
**Describe the bug**
The turbine continues to execute the recipe, without the rotor.
The bug works in solo and on the server

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.8.599
CodeChickenLib: 1.12.2-3.2.3.358-universal
CraftTweaker2: 1.12-4.1.20.586

**Steps To Reproduce**
1) Build a plasma turbine (this is clearly visible on it, because of the duration of the recipe)
2) Run the recipe
3) Pull out the rotor

**Screenshots**
![image](https://user-images.githubusercontent.com/44977883/103022662-057a5b00-457f-11eb-8c76-a15c608c7501.png)

Took the holder while retaining the NBT
![image](https://user-images.githubusercontent.com/44977883/103025033-96ebcc00-4583-11eb-8978-88436de8e2ba.png)

Took the same holder after about 10 seconds
![image](https://user-images.githubusercontent.com/44977883/103025057-a1a66100-4583-11eb-9746-da97e08a6742.png)

**Additional context**
The turbine does not generate power, without a rotor.

Moreover, the controller remains active after the rotor is removed.
In addition, when you stop the process with a soft-hammer, the work stops, but the controller texture remains active.

It seems to me that the problem is with the controller than with the rotor holder. Controller activity is the cause, and continued overclocking is the consequence.

**Comment by ALongStringOfNumbers** [comment]
I will confirm that stopping the turbine with a soft hammer does not update the controller, but it does stop the rotation speed from increasing, and instead the rotation speed goes to 0. From some slight debugging, it appears that the multiblock still has `WorkingEnabled` set to true, even if the multiblock is stopped by a soft hammer

**Comment by LAGIdiot** [comment]
Accepted base on provided data. Further investigation regarding what all is not working as expected is required.

**Comment by ALongStringOfNumbers** [comment]
The Rotor increasing its speed/maintaining its speed if it was at maximum when removed from the rotor holder can be solved by adding a check to `isActive` in `MetaTileEntityLargeTurbine` to check if there is a rotor in the holder.

However, the fact that the controller remains active when the rotor is removed, and also remains active when the rotor reaches zero speed even when removed from the holder remains an issue. I think this is because of the fact that the rotor holder overrides the `update` method to increment/decrement the speed of the rotor based on if the controller is active, but never has a case to handle if there is no rotor (aka if it was removed), and cannot set the controller to be not active. Therefore, the controller will never change its active state.
