### ISSUE TITLE
[BUG] Cracker Unit is not shown formed in JEI

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1379]
**Describe the bug**
The Cracker Unit is not shown as formed in JEI, such that the inputs and the outputs take the casing texture.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.8.599
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Open Jei and look at the Cracker Unit preview in JEI

**Expected behavior**
That the Cracker Unit is shown formed in JEI

**Screenshots**
![2021-01-01_14 05 49](https://user-images.githubusercontent.com/31759736/103446239-8948dd00-4c3a-11eb-8c94-41fa21db0069.png)

**Comment by LAGIdiot** [comment]
Accepted base on provided image.

Cracker Unit should be shown as formed in JEI.

**Comment by warjort** [comment]
The issue here is that MultiblockShapeInfo is placing the same tile entity for hatches with the same symbol.
It is effectively creating "ender hatches". :-)

For the cracker the
````
 .where('F', MetaTileEntities.FLUID_IMPORT_HATCH[GTValues.HV], EnumFacing.EAST)
````
is used twice.

When the controller checks for the minimum number of recipe inputs, it adds the hatches multi[;e times, but since they have the same underlying fluid tank there are not enough tanks to satisfy the requirements.

The cracker just happens to be the only one with >=2 minimum fluid input requirements  in its recipe maps.
For items, it checks the slots and 16 slots per bus will always be enough.

The following patch fixes the problem. It duplicates the tile entities as they are baked into the multiblock blockinfo array.
But it feels a bit hacky since the code is already doing this in the where() method, but that is the wrong place - it is too early.
````
diff --git a/src/main/java/gregtech/integration/jei/multiblock/MultiblockShapeInfo.java b/src/main/java/gregtech/integration/jei/multiblock/MultiblockShapeInfo.java
old mode 100644
new mode 100755
index 007be078..1a3429a0
--- a/src/main/java/gregtech/integration/jei/multiblock/MultiblockShapeInfo.java
+++ b/src/main/java/gregtech/integration/jei/multiblock/MultiblockShapeInfo.java
@@ -5,6 +5,7 @@ import gregtech.api.metatileentity.MetaTileEntityHolder;
 import gregtech.api.util.BlockInfo;
 import gregtech.common.blocks.MetaBlocks;
 import net.minecraft.block.state.IBlockState;
+import net.minecraft.tileentity.TileEntity;
 import net.minecraft.util.EnumFacing;
 
 import java.util.ArrayList;
@@ -64,6 +65,15 @@ public class MultiblockShapeInfo {
                     BlockInfo[] columnData = new BlockInfo[columnEntry.length()];
                     for (int k = 0; k < columnData.length; k++) {
                         columnData[k] = symbolMap.getOrDefault(columnEntry.charAt(k), BlockInfo.EMPTY);
+                        TileEntity tileEntity = columnData[k].getTileEntity();
+                        if (tileEntity != null) {
+                            MetaTileEntityHolder holder = (MetaTileEntityHolder) tileEntity;
+                            final MetaTileEntity mte = holder.getMetaTileEntity();
+                            holder = new MetaTileEntityHolder();
+                            holder.setMetaTileEntity(mte);
+                            holder.getMetaTileEntity().setFrontFacing(mte.getFrontFacing());
+                            columnData[k] = new BlockInfo(columnData[k].getBlockState(), holder);
+                        }
                     }
                     aisleData[j] = columnData;
                 }
````
