### ISSUE TITLE
[Suggestion]Is there something like a voltmeter?

### ISSUE THREAD

**Issue by TokunagaKen** [GregTechCE/GregTech#1411]
Minecraft 1.12.2
Gregtech CE 1.10.9.612
IC2ex 2.8.170-ex112

Is there a device that can measure the current and voltage flowing through the conductor? I couldn't use the IC2 voltmeter in my environment.

Gregtech CE's steam and power system is complex. But I think that's the good thing about this mod.
However, it is a problem that we do not understand why the machine is running out of power. Because you don't know what you're missing and you lose track of Gregtech's goals.
I feel that there is not much information to do the loss calculation of the electric cable. To solve this problem, I think you need a handheld device such as an IC2 voltmeter.

Thank you for your consideration.

Please let me know if it is already implemented.

**Comment by LAGIdiot** [comment]
GTCE energy system works quite differently from IC2 and we have no compatibility with it. So that is why IC2 voltmeter can't work on GTCE.

You can use this crude explanation how GTCE electricity works for now: https://ftb.gamepedia.com/Getting_Started_(GregTech_Community_Edition)#How_electricity_works .
And we will think about providing better guide in future.

Currently we are not planning to add Voltmeter
