### ISSUE TITLE
[Suggestion] Allow any item in the "Charger" Slot in machines

### ISSUE THREAD

**Issue by DStrand1** [GregTechCE/GregTech#1436]
**Is your feature request related to a problem? Please describe.**
In previous versions of GregTech, there was a really nice, convenient feature that you could store any item in the "charger" slot in GT machines. This is especially nice for machines like the Fluid Solidifier, or the Extruder, where you often times have many molds and shapes sitting around. Also, for integrated circuits, its nice to store one here if you are often needing one or two of them for a machine (Assembler, Bending machine, etc).

**Describe the solution you'd like**
Allow any item in the "charger" slot, instead of requiring an `IElectricItem`.

**Additional context**
It's such a small change, that I don't see any reason why it shouldn't be allowed, but I figured I'd make an issue for it anyway, as there may be some reason why this feature was removed.

**Comment by Archengius** [comment]
No. If you feel like improving usability, consider doing it some civil way, instead of falling back to GT5U "if it's there, it's a feature" design philosophy. Charger slot's purpose is charging items, not storing items.

I would rather suggest 2 possible solutions that make much more sense:
1) Add inventory extension on the left side of the fluid solidifier/extruder UIs, capable of storing fixed amount of forms.
2) Allow conversion of the forms in-place by adding a small UI element when you click on the desired form and it  transforms currently existing form into the new one - inspired by FTBI.

And regarding integrated circuits, it might be a good idea to add small widget into the machine which will allow changing their configuration right inside of the machine UI.

**Comment by warjort** [comment]
My 2 cents. :-)

If this "inventory extension" is made into a capability it could be activated "programmatically" by automation.
e.g. You could have a cover that changes the recipe selector based on redstone signal, 0 = no selector, 1 = slot 1 in the new UI, etc.

I would even suggest putting the UI in the cover. 
i,e. the new capability just has to deal with swapping the recipe selector supplied by its user.
This would allow alternate implementations; UI, or redstone signal or something else...

**Comment by LAGIdiot** [comment]
I am definitely against using charger slot to be storage for everything. Design behind it is to simple charge items. If you fell like you need place for molds, please open issue for it and we can brainstorm something. But there will be no butchering of charger slot.
