### ISSUE TITLE
[BUG] GT JEI plugin incompatible with mod Valkyrien Skies

### ISSUE THREAD

**Issue by lordmuff** [GregTechCE/GregTech#1450]
**Describe the bug**

When installed with the mod Valkyrien Skies (divided into it's submods Valkyrien Skies, Valkyrien Skies Control, and Valkyrien Skies World), GTCE's JEI integration fails to work as intended. Missing recipes, JEI multiblock info does not show up.

**Versions**
Forge: forge-14.23.5.2855
GTCE: gregtech-1.12.2-1.11.1.632.jar
Addons: MultiblockTweaker

**Setup**
Playing Solo

**Steps To Reproduce**
1) Install the Valkyrien Skies mods alongside GTCE and JEI
2) Boot up game
3) Load into a world and open JEI

**Expected behavior**
For recipes and multiblock info to be visible in JEI

**Additional context**
I first encountered this in a homemade pack with Gregicality, but upon further inspection it also seemed to happen WITHOUT Gregicality installed, so I was directed to post it here.

**Comment by Archengius** [comment]
You need to attach a log file at least.

**Comment by lordmuff** [comment]
ah, my bad. here it is:
[latest.log](https://github.com/GregTechCE/GregTech/files/5938382/latest.log)

**Comment by eutropius225** [comment]
Are you sure you managed to download the mod (Valkyrien Skies) correctly? The log mentions errors reading class files, which suggests corruption.

**Comment by warjort** [comment]
I can reproduce this with just the Valkyrien Skies mod (other mods not required) and GTCE. 
I also get the class and signature errors using the latest version from curseforge.

None of the GTCE categories or catalysts are in JEI. It's like the JEI plugin never gets invoked.
I added Bonsai Trees 2 to the modpack and its JEI plugin is working ok.
So JEI is not generically broken.

From what I can see there is no reference to JEI in the VS mod. So this must be a side effect of something else.
Probably one of the mixins or the FMLLoaderPlugin it is installing.

I tried to build the Valkryien Skies mod from scratch to see if that would fix it, but there is 530 error accessing the maven repo for one of its dependencies, maybe I will try again later.

**Comment by warjort** [comment]
Of course, I also had to add MixinBootstrap to the modpack (for some reason VS does not specify the dependency). 
But just running with this and without the VS mod did not cause the problem.

**Comment by Archengius** [comment]
`
Caused by: java.lang.IllegalStateException: World gregtech.api.render.scene.WorldSceneRenderer$TrackedDummyWorld@57099e07 doesn't have an VSWorldDataCapability. This is wrong!
	at org.valkyrienskies.mod.common.util.ValkyrienUtils.getWorldDataCapability(ValkyrienUtils.java:127) ~[ValkyrienUtils.class:?]
	at org.valkyrienskies.mod.common.util.ValkyrienUtils.getQueryableData(ValkyrienUtils.java:142) ~[ValkyrienUtils.class:?]
	at org.valkyrienskies.mod.common.ships.QueryableShipData.get(QueryableShipData.java:81) ~[QueryableShipData.class:?]
	at net.minecraft.world.chunk.Chunk.handler$zzl000$pre_setBlockState(Chunk.java:1711) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:343) ~[amu.class:?]
	at gregtech.api.render.scene.WorldSceneRenderer$TrackedDummyWorld.func_180501_a(WorldSceneRenderer.java:299) ~[WorldSceneRenderer$TrackedDummyWorld.class:?]
`
Yet another mod hooking into the internal chunk-related methods and raining exceptions just because it didn't expect the world to be not a real dimension. 
This will not be fixed, valkyrienskies should stop hooking into world-related methods and throwing exceptions when stuff does not go in the way it expects.

**Comment by eutropius225** [comment]
The issue is that GregTech is creating worlds wrong. Valkyrien Skies expects, quite reasonably, that any worlds that are created will fire the appropriate world creation events, so that it can [attach its capabilities](https://github.com/ValkyrienSkies/Valkyrien-Skies/blob/f6301d38fbc0c4b68e1cf4ee3f61a3f7c4b27461/src/main/java/org/valkyrienskies/mod/common/capability/VSCapabilityRegistry.java#L32).

It's quite funny, actually, as you can see they left a [nice comment](https://github.com/ValkyrienSkies/Valkyrien-Skies/blob/069504632e1f0881cab6c96aaef9f30df82ca4c7/src/main/java/org/valkyrienskies/mod/common/util/ValkyrienUtils.java#L124-L126) explaining their opinion.

**Comment by Archengius** [comment]
Gregtech is not calling these events because that world is a FAKE world and exposing it to other mods in any way (especially by calling events) will make the situation even worse. If you happen to introduce custom patches into the core world methods, can you please at least make sure they work in all the cases where vanilla does?
This mod does literally the opposite thing: it crashes in a completely valid place from vanilla's point of view, and ACTUALLY blames other mods for not handling it's random patch properly.

**Comment by eutropius225** [comment]
> can you please at least make sure they work in all the cases where vanilla does?
That's exactly what it does. It works with Vanilla (as patched by Forge), and anything that replicates it by properly calling the event.

In any case, I don't see why you closed this issue, when it's a bug that exists. If it's not for us to fix then it should be reported on their issue tracker, [as it has been](https://github.com/ValkyrienSkies/Valkyrien-Skies/issues/477), and discussed with them so a solution can be found.

**Comment by Archengius** [comment]
> That's exactly what it does. It works with Vanilla (as patched by Forge), and anything that replicates it by properly calling the event.

I don't need to call that event to have Chunk#setBlockState working in vanilla. If your patch requires me to do so to avoid getting a crash, your patch is wrong.

**Comment by eutropius225** [comment]
That's a bad argument.

I could also instantiate a class without calling its constructor using Unsafe, JNI or other awful things. I might even be able to invoke certain methods, like `setBlockState`, on it without an issue in Vanilla. Your patch breaks that? It must be your fault.

**Comment by Archengius** [comment]
No, it's making an unreasonable decision to hook an important method and crash just because it can instead of handling it gracefully. Don't see anything to discuss there.
