### ISSUE TITLE
[Suggestion] Move Rotor Mold Recipes to LV

### ISSUE THREAD

**Issue by DStrand1** [GregTechCE/GregTech#1491]
After implementing the Rotor Mold, there was a slight unintended side effect of its development process. Since it was originally implemented as an Extruder Shape, I had its EU/t set at MV. However, now that it is a Mold (and the only machine recipe for rotors), I think this should be moved to LV. Thoughts?

Additionally, here is the issue where this discussion first came up:
https://github.com/OmnifactoryDevs/Omnifactory/issues/696

**Comment by Exaxxion** [comment]
This should be a simple change to implement as it's just altering the EU/t but keeping the recipes otherwise unchanged. We would appreciate knowing whether you're interested in this change as it would inform whether Omnifactory needs to implement custom recipes for at least those rotors players might need to make at LV.

**Comment by LAGIdiot** [comment]
This is definitely oversight on my end. Mold recipe should be in similar range as others. Even though this is more complex then other it should not cost more then LV can handle.
