### ISSUE TITLE
[Suggestion] chemical formula for liquids

### ISSUE THREAD

**Issue by million09** [GregTechCE/GregTech#1510]
**Is your feature request related to a problem? Please describe.**
I sometimes confuse `Hypochlorous Acid` and `Hydrochloric Acid`. `HClO` and `HCl` are easy to distinguish.

**Describe the solution you'd like**
Add tooltips for chemical formula of liquids, like dust / ingot materials have.
This will improve QoL for chemistry.

**Comment by DStrand1** [comment]
I would love to implement this feature, but have not been able to implement it as of yet. If you’ve seen any mod in 1.12 that has proper tooltips for fluids (and not just the bucket of a fluid), please let me know as that could potentially help solve this issue.

**Comment by DStrand1** [comment]
On some further thought,  a lot of digging around through other mods, and talking with much better modders than I, I think this *is* possible, though it is a quite difficult implementation so don't expect this feature for at least another release or two.

**Comment by LAGIdiot** [comment]
This seems like good idea which could help some players. So I am in favor accepting it.

Regarding implementing tooltips for liquids I was trying to do it for showing temperatures but I got nowhere. I am not saying it is impossible but not easiest thing either.

**Comment by DStrand1** [comment]
I have been able to get this working in some cases, and I know it to be possible in others but have not yet implemented it.

Since Minecraft and Forge don’t expect the player to have a FluidStack in their inventory, adding tooltips to fluids is far from trivial. In order to pull this off thoroughly, there are in my opinion 4 key places to ensure the tooltip appears:
- TankWidget hover, in GTCE machines
- JEI hover in recipes and on fluids
- Minecraft Buckets
- GTCE Cells and others like them

Currently, I have this feature fully implemented for the TankWidget, and for the Minecraft Buckets. GTCE cells are next, and I am just working through NBT data to get it finished. The JEI portion is definitely possible, but will take some time.

Here’s an example of a MC bucket with a tooltip:
![A2AF3F0A-7606-45C9-8533-351F2E98470B](https://user-images.githubusercontent.com/10861407/110236749-353dcb80-7efd-11eb-8726-666d541fb14d.png)
