### ISSUE TITLE
[BUG] Transformer Top Info trying to translate on the server

### ISSUE THREAD

**Issue by warjort** [GregTechCE/GregTech#1512]
**Describe the bug**
The TOP TransformerInfoProvider introduced in #1404 has the same issue as that fixed in #1511

**Comment by LAGIdiot** [comment]
**Version:**
Forge: 14.23.5.2847
GTCE: 1.12.0 (dev build on 011334576ccb057cc7b3190503520798e3b6ee08)

**Enviroment:**
GTCE dev
Dedicated server

**Outcome:**
Bug confirmed

**Comment by LAGIdiot** [comment]
@DStrand1 can you please take a look at this? You should be able to fix it similarly as in #1511

**Comment by DStrand1** [comment]
PR #1467 changes lang entries that I would then have to change again to make this fix. I will do this fix quickly for next release if you want me to, but these PR's would introduce some silent merge issues if they are both included since I will have to rename the lang entries and add new ones in my fix.
