### ISSUE TITLE
[Suggestion] Allow Quantum Containers to Keep Inventory on Break

### ISSUE THREAD

**Issue by DStrand1** [GregTechCE/GregTech#1530]
**Is your feature request related to a problem? Please describe.**
Historically (and currently), both Quantum Tanks and Chests destroy their contents when broken. I believe the primary reason for this being the case in GT5 was because at the time, these storage options were *very* strong, having significantly more storage than other options available. However, in modern modded, this just does not seem to be the case anymore. Storage Drawers are cheaper than Quantum Chests, and can easily hold more than enough items in them. And similarly, ExtraCells 1k Fluid Drives can hold even more than the early tiers of Quantum Tanks.

**Describe the solution you'd like**
I would like to open the discussion on changing this, and allow for these storage options to keep their inventory on break. As far as implementation goes, this would be trivial. Though, this is a relatively significant change, so I want to know some opinions before writing the change.

**Additional context**
A suggested idea to balance it somewhere in-between was to not allow Quantum Tanks and Chests to have any more items/fluids input into them after moved until they are fully emptied first. This way, the player can still move the container safely if they put it in a bad spot, but they cannot do it for free.

**Comment by ALongStringOfNumbers** [comment]
I will say I am in favor of having the Tanks and Chests keep their inventories, to prevent players from using them for storage and then losing their items when breaking them if they are unaware of the voiding.

I am also in favor of the balance note of having them not accept any more items/fluids after being moved (until emptied), because it turns the Quantum Tank/Chest into an extract only cache, which does not punish players by having them lose their items/fluids, but also means that they will still have to think about how to place and organize the containers. If this feature is used though, it will need to be conveyed to the players, perhaps through a tooltip.

**Comment by Chezzik** [comment]
I'm in favor of them keeping their inventories.  

If we do that, a recipe should be implemented that allows the player to void the inventory easily by clearing the NBT data.  Basically, Quantum Tank w/ NBT data becomes Quantum Tank without NBT data.  Many other mods have begun doing this (Ender IO is an example), and I think it's a good precedent to follow.

**Comment by DStrand1** [comment]
> If we do that, a recipe should be implemented that allows the player to void the inventory easily by clearing the NBT data. 

I definitely agree, it should not be difficult to implement.
