### ISSUE TITLE
[BUG] GT cables aren't craftable.

### ISSUE THREAD

**Issue by BrewishSpermazist** [GregTechCE/GregTech#1543]
I've installed GT CE v.669 with the IC2 2.8.197-ex112 on 1.12.2 and when I have had to craft tin cable I could only craft IC2's tin wire.
I used all of instruments, cutter from IC and such one from GT, industrial craft table and crafting station. In all cases I could only craft IC's cable.
Should I change GT version to the older one?

**Versions**
Forge: 
GTCE: 669
IC2 2.8.197 ex112

Screenshot related
![2021-03-22_16 35 24](https://user-images.githubusercontent.com/81168588/111998138-c5e6ef00-8b2c-11eb-95bd-2e4f581e5124.png)

**Comment by warjort** [comment]
This is just a recipe conflict.
IC2 and GTCE say a tin plate + wire cutters make different items.

If you don't want to play around with crafttweaker to change one of the recipes to resolve the conflict, you could always try
a mod like this: https://www.curseforge.com/minecraft/mc-mods/stimmedcow-nomorerecipeconflict

The conflict is almost certainly because historically GregTech started as an addon to IC2.
