### ISSUE TITLE
Diatomic elements not accounted for in reactions

### ISSUE THREAD

**Issue by lawremi** [GregTechCE/GregTech#1575]
As everyone knows, the elements hydrogen, nitrogen, oxygen, fluorine, chlorine, iodine, and bromine are diatomic, i.e., the exist in nature as pairs of atoms. However, the GT reactions are balanced as if they have only a single atom. The electrolysis of water is one example. Fixing this may throw off the balance a bit, but it would make the chemistry a lot more consistent with reality.

**Comment by DStrand1** [comment]
I understand your explanation, and believe me, I would like for diatomicity to be properly respected. However, to simplify things for our chemistry and the chemistry of our addons, we had to draw the line somewhere.
We have just recently fixed all of our stoichiometry, and similarly in addons, which has been a project since January. Personally I do not feel that addressing this is urgent because of these reasons.

**Comment by lawremi** [comment]
Thanks for the response. I'd like to understand the difficulties involved. How much of this is embedded in the logic vs. manual updating of recipes?

**Comment by pablocnvs** [comment]
It was all manual, probs being one of the biggest PRs done. For context, it was a full update in Gregicality (one of the addons). If we applied this rule, we would also need to account for phosphoruous being P4 and sulfur being S8 which is too much for that. Also, since molecules are so tiny, you can think that it is diatomic just with half the amount of moles. And since making things diatomic would involve multiplying by two, once you have done 2 recipes it is the same.

**Comment by lawremi** [comment]
Good points. I'd be happy to do the manual work. I agree though that there's no real effect on gameplay, it's mostly aesthetic.
