### ISSUE TITLE
[BUG] Ice fluid extracts into useless fluid

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1608]
**Describe the bug**
The Ice block fluid extracts into 144mb of liquid ice, which has no use in GTCE. 

**Versions**
Forge: 14.23.5.2847
GTCE: 1.14.1.705
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Look at the Fluid Extraction recipe for ice
2) See the weird amount and that liquid ice has no usages

**Expected behavior**
I would expect ice to fluid extract into the normal amount of fluid for a block, and for liquid ice to have a use. For liquid ice, I would suggest just adding a Fluid Heater recipe to transform it into water.

If the fluid extraction amount is changed, the fluid solidification amount would need to change as well, as well as the fluid extraction recipe of packed ice.

**Comment by warjort** [comment]
The amount appears to be a deliberate choice:
https://github.com/GregTechCE/GregTech/blob/ccc9e3b2a6e53b5a973c3cad1cbf0968fc7764d5/src/main/java/gregtech/api/unification/ore/OrePrefix.java#L358

It seems to be trying to represent "low density" materials.

But I don't think it is very realistic for ice.
Water is weird in that the solid is less dense the liquid (which is why ice floats), but it is only marginally so (0.916 vs 0.997 g/cm3)

**Comment by warjort** [comment]
"Liquid ice" is of course just water which makes the whole thing weirder :-)

**Comment by DoctorWeirdGuy** [comment]
Liquid ice (which when googled gives you vape crap) might as well just be supercooled water.

**Comment by ALongStringOfNumbers** [comment]
This appears to be a Forestry compat item, because with Forestry installed as well, there is a fluid Solidification recipe added for the liquid ice (Now registered under Crushed Ice once Forestry is installed)
