### ISSUE TITLE
[BUG] Implosion Compressor No Longer Stores Explosives as Property

### ISSUE THREAD

**Issue by DStrand1** [GregTechCE/GregTech#1614]
**Describe the bug**
Since the addition of the new recipe properties in #1580, the implosion compressor now does not store its explosives as a property for the recipe. You can see [here in Gregicality](https://github.com/Gregicality/gregicality/blob/d1883fed1778ffec09215275ab93a8abcf1aac14/src/main/java/gregicadditions/recipes/categories/handlers/ElectricImplosionHandler.java#L59) that we are depending on this property for some of our recipe generation. As a result it is impossible to discern what is an explosive and what is an input for the Implosion Compressor. This code works for any version prior to 1.15.0.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.15.0
_Addons:_ None required, but tested with Gregicality

**Expected behavior**
Implosion Compressor should store explosives as a recipe property as well as a recipe input

**Comment by ALongStringOfNumbers** [comment]
Personally, I believe that all these properties using the old system still in GTCE, like the Implosion Compressor, Fusion Reactor, Amplifier, should be updated to the new system so that things are not split between two different systems in GTCE.

For those properties that should not display anything in JEI, like the Implosion Compressor, the `drawInfo` override can simply draw an empty String.

For those properties not implemented by GTCE, such as fusion, having the newer system to simply extend and override methods as required would be simpler than trying to deal with the property being assigned in the constructor, <https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/recipes/builders/FusionRecipeBuilder.java#L21>. For these properties that are not implemented, simply having the required method stubs and `drawInfo` defaulting to displaying nothing would be a much easier way of implementing these properties.

**Comment by Exaxxion** [comment]
> For those properties that should not display anything in JEI, like the Implosion Compressor, the drawInfo override can simply draw an empty String.

That seems like an awkward mechanism for such behavior. It would make more sense to explicitly mark a RecipeProperty as hidden or unreported or whatever you want to call it, rather than use a special value of a String that happens to produce the behavior (for now at least, and in some specific code) as a side effect of the current implementation.

The RecipeProperties rework has caused several problems due to breaking API changes. Unfortunately the addon mods are just going to have to mandate a dependency version of at least 1.15.0.721 and change the implementation to work with the new system. In the future we should do more extensive testing to find issues like these.

**Comment by detav** [comment]
> Since the addition of the new recipe properties in #1580, the implosion compressor now does not store its explosives as a property for the recipe.

This is something I got asked on the original pr, [it never did](https://github.com/GregTechCE/GregTech/blob/f0ee6248a7ee29177b326830561ffd1176ca7e75/src/main/java/gregtech/api/recipes/builders/ImplosionRecipeBuilder.java#L87).

> That seems like an awkward mechanism for such behavior.

The way drawInfo works is the same as [before](https://github.com/GregTechCE/GregTech/blob/d3e9f17afe622bb4d68d62305ca87176fd85660c/src/main/java/gregtech/integration/jei/recipe/GTRecipeWrapper.java#L138).

**Comment by detav** [comment]
> The RecipeProperties rework has caused several problems due to breaking API changes.

From what I've seen, maybe i am wrong, the problems are caused from a deleted method?. That should be easy to hotfix.

**Comment by Exaxxion** [comment]
> From what I've seen, maybe i am wrong, the problems are caused by a deleted method?. That should be easy to hotfix.

The point is that it was an inadvertent breaking API change. Mods not only have to "hotfix" it (and we already have in some cases) but also the mods must mandate loading a specific minimum version of GTCE whereas simply deprecating and re-routing the old method would have permitted the existing versions of mods to continue functioning as before without an emergency hotfix release.

> The way drawInfo works is the same as before.

Ok? I still think it sounds like a faulty implementation.

**Comment by DStrand1** [comment]
> This is something I got asked on the original pr, [it never did](https://github.com/GregTechCE/GregTech/blob/f0ee6248a7ee29177b326830561ffd1176ca7e75/src/main/java/gregtech/api/recipes/builders/ImplosionRecipeBuilder.java#L87).

While it may not be registered there before, I can confirm that the code I referenced in my opening comment worked before, and can be tested and proven easily with GTCE 1.14.1 or earlier, and any recent version of Gregicality. Now in 1.15.0, there are no properties on Implosion recipes. And either way, I think it is fair to say that it should be a property now

**Comment by detav** [comment]
> The point is that it was an inadvertent breaking API change. Mods not only have to "hotfix" it (and we already have in some cases) 

Yes, I agreed with you. I meant that GTCE has to be hotfixed.

> While it may not be registered in that exact spot before, I can confirm that the code I referenced in my opening comment worked before

Sure, but the bug is not that it is no longer stored, so it is somewhere else, maybe it was a bug before lol.

**Comment by Exaxxion** [comment]
> Yes, I agreed with you. I meant that GTCE has to be hotfixed.

Sorry then, I misunderstood what you meant.

Given that the major addon mods have already responded to the change it's perhaps a bit late for a GTCE hotfix to matter. I agree with ALSON in that it's probably best to port things to the new system rather than trying to fix the deprecated one.

**Comment by LAGIdiot** [comment]
Honestly I already forgotten that there was such mechanic for Implosion Compressor. And I have to miss it when I was converting all (only machines we provide with recipes) to new system. Probably because it was not registered in "standard" way. And when I look at it now I am quite surprised it did even work when it was passing in empty map of recipe properties.

I think we should rework Implosion Compressor because I feel way we pass in explosives now is awkward and let us to this problem.

**Comment by LAGIdiot** [comment]
> The RecipeProperties rework has caused several problems due to breaking API changes. Unfortunately the addon mods are just going to have to mandate a dependency version of at least 1.15.0.721 and change the implementation to work with the new system. In the future we should do more extensive testing to find issues like these.

You did not have to upgrade immediately did you? We can work it out, polish it before you start using it right?

**Comment by Exaxxion** [comment]
Players were encountering problems like https://github.com/eutro/MultiblockTweaker/issues/14 and we've already done the relevant workarounds a few days ago. As far as a more in-depth transition to the new system, certainly that should be done with less haste.

**Comment by LAGIdiot** [comment]
> Players were encountering problems like [eutro/MultiblockTweaker#14](https://github.com/eutro/MultiblockTweaker/issues/14) and we've already done the relevant workarounds a few days ago. As far as a more in-depth transition to the new system, certainly that should be done with less haste.

I saw that one and I checked fix for it and removing `recipe.getPropertyKeys()` was certainly mistake and I did not plan to remove that, it should just get deprecated.

But I am concern regarding how everyone has dependencies setup as it was release as minor. Your not locking dependencies from top too?

**Comment by DStrand1** [comment]
For Gregicality, we had to update and require minimum version of 1.15.0, but also because the changes to SlotWidget introduced a couple other breaking changes for us due to the change in the return type of `getHandle()`.
