### ISSUE TITLE
[BUG] Issue with the Ore Generation Page and Advanced Rocketry

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1669]
**Describe the bug**
Ore veins set to generate on AR planets do not show the dimension in the list of dimensions that the ore will generate in.

Another minor thing, Some veins are shown that they can generate in the AR "Space" dimension. I believe that this happens with veins that are set to spawn in the overworld. It should be checked if anything can even spawn in the "Space" dimension (Are asteroids a separate dimension?) and if not, then the "Space" dimension information should not be shown.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.15.1
_Modpack:_ Non3
_Addons:_ None
AR: 2.0.0-250
LibVulpes: 0.4.2-83

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Add a vein to generate specifically in an AR dimension (dimension ids found in planetDefs.xml in the world save folder)
2) See that the dimension is not listed on the ore generation page with the vein

**Expected behavior**
For the dimension to show on the ore generation page

**Additional context**
While debugging another issue, I found that this was because at the time of loading, the registered dimensions only included the vanilla dimensions and the AR "Space" dimension. There was no list of the various planet dimensions anywhere in the list of registered dimensions, causing no dimension to be displayed

**Comment by warjort** [comment]
Isn't the issue here, in this code:
https://github.com/GregTechCE/GregTech/blob/dde025306a81abf2d7ad10561fcd3553805ca17e/src/main/java/gregtech/integration/jei/GTOreInfo.java#L90

Roughly speaking the order of the forge event model is:
* Mod initialisation
* Generic initialisation (relevant here resource loading, e.g. textures or recipes)
* Game instance (server) initialisation

The JEI initialisation happens during the generic initialisation. JEI hooks into to end of the resource reloading to run the plugins

But the code above is asking for game instance specific data before it has been initialised
In particular the AR dimensions that are not initialised until "server starting".

There is a special case for the "space" dimension which is always initialised in AR's mod "post init".

It seems to me that doing JEI initialisation based on game instance specific data is just wrong.
This data can vary across saves. e.g. one save can have one set of dimensions, while another has different dimensions.

I would think the best you can do is to load all the ore vein definitions into JEI and then do something at runtime to indicate the dimension is not availble in this save.
A simple way would be rendering some big red flashing text across the recipe. :-)
But you might be able to do better than that?

**Comment by warjort** [comment]
I believe AR has some extra dynamicity when it comes to dedicated server mode.
When a client joins a server, it is sent network messages telling it what dimensions are available.
So even the local configuration on the client might not be relevant when JEI is being configured?
