### ISSUE TITLE
Large Turbines missing Parenthesis in EU/t Output computation

### ISSUE THREAD

**Issue by Andrakax** [GregTechCE/GregTech#1678]
Describe the bug
The EU/t output of the Gas and Steam turbines do not match what is advertised based on wiki.  So I pulled up the code and there appears to be a missing set of parenthesis, I think.  Not sure how the code reads, but normal Order of Operations would require the additional set of parenethesis.

Current code: 
`double totalEnergyOutput = (BASE_EU_OUTPUT + getBonusForTurbineType(largeTurbine) * rotorEfficiency) * (relativeRotorSpeed * relativeRotorSpeed);`

What it probably should be:
`double totalEnergyOutput = ((BASE_EU_OUTPUT + getBonusForTurbineType(largeTurbine)) * rotorEfficiency) * (relativeRotorSpeed * relativeRotorSpeed);`

GTCE: 1.15.0
Gregicality: 0.22.6.2

**Comment by Exaxxion** [comment]
What wiki are you referring to? [Our wiki](https://github.com/GregTechCE/GregTech/wiki) doesn't have any information related to turbines.

**Comment by Andrakax** [comment]
https://ftb.fandom.com/wiki/Large_Turbine_(GregTech_Community_Edition)

Most of the way down there is a section for Max Energy Output.  It shows the following equation.

![image](https://user-images.githubusercontent.com/79467032/123860758-5420fd00-d8f4-11eb-8d24-a4411dd35192.png)

**Comment by warjort** [comment]
The logic for the rotor efficiency only applying to the bonus energy hasn't changed since it was first implemented.

https://github.com/GregTechCE/GregTech/blob/1216c7dbe000c57e5334b62177c8277fcc7352d6/src/main/java/gregtech/common/metatileentities/multi/electric/generator/LargeTurbineWorkableHandler.java#L56

Saereth's change just makes the bonus configurable.

**Comment by Andrakax** [comment]
As it currently is (assuming normal Order of Operations and that java reads the multiplication before the addition) the rotor efficiency boost is only being applied to the turbine bonus EU/t and not to the BASE_EU_OUTPUT.

**Comment by Exaxxion** [comment]
Disregarding the wiki (frankly it's irrelevant what they claim it is) it does seem a little weird that only the output bonus is modified by rotor efficiency.

That's why I'm saying we should see what LAG thinks about it. It's possible it's working exactly as intended and the answer is simply just "whoever wrote that wiki page is wrong."
