### ISSUE TITLE
Unable to craft LAPIS ROD [BUG] 

### ISSUE THREAD

**Issue by Muss217** [GregTechCE/GregTech#1761]
I am unable to craft rods with lapis, lazurite or sodalite. This makes it impossible to craft the Lapatron Crystal. 

**Versions**
Forge: Minecraft 1.12.2
GTCE: Version 1.6.6.374
https://www.curseforge.com/minecraft/modpacks/gregblock

Playing Solo

**Comment by Exaxxion** [comment]
The pack you are playing hasn't been updated since 2019, and is consequently using an extremely old version of the mod. I would suggest cheating the item in for your playthrough if you plan to complete it, as it would almost certainly break a lot of things to update GTCE yourself.

I would recommend playing more recently updated GregTech packs in the future. The version of this mod that packs should be using these days is 1.17.1, the final release from October 2021.

**Comment by Muss217** [comment]
Thank you for the response. I have been playing this pack on and off for a few years now and have never reached this point in the progression. I would rather not restart. It appears that the item is not one that I can cheat into the game. Do you think that it's doomed or is there something else I can do?

**Comment by Muss217** [comment]
Scratch that! I just went into creative and got a stack of rods. Thanks for the help!
