### ISSUE TITLE
Rubber tree sapling texture is bigger than the block

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#214]
![2018-07-11_07 56 46](https://user-images.githubusercontent.com/34199560/42544142-32eaed44-84e2-11e8-982c-5d4187f09b6c.png)
The black line is the size of a normal block.
Mod list:
jei_1.12.2-4.11.0.202
gregtech-1.12.2-0.4.5.9
CodeChickenLib-1.12.2-3.2.0.345-universal
forge1.12.2-14.23.4.2705

**Comment by SuperCoder7979** [comment]
I stole the texture from GT6, so blame greg, and also it doesn't hurt having a little variety.

**Comment by leagris** [comment]
@SuperCoder7979 The issue is not the texture size but the wierd UV Mapping that's stretching 16×14 pixels from a 16×16 pixels icon: ![](https://raw.githubusercontent.com/GregTechCE/GregTech/master/src/main/resources/assets/gregtech/textures/blocks/wood/rubber/sapling_rubber.png) onto a space that's for 16x16 pixels, stretching to non-square pixels and cropping the picture asset first and last pixels columns. And I know it is not your fault but how is the `minecraft:cross` model coded:

Not how the panes spans horizontally from 0.8 to 15.2 but the UV Map includes all the 16×16 area. The Rescale flag, then causes the pane to be scaled up so it meets with full block size horizontally and once rotated.
You don't really see the effect with vanilla saplings because the top 3 pixels are transparent.
Here, all picture height contains pixels and you can now see the top 3  pixel rows above the block highlight box.

Here the minecraft:cross JSON model source:
```JSON
{
    "ambientocclusion": false,
    "textures": {
        "particle": "#cross"
    },
    "elements": [
        {   "from": [ 0.8, 0, 8 ],
            "to": [ 15.2, 16, 8 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45, "rescale": true },
            "shade": false,
            "faces": {
                "north": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross" },
                "south": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross" }
            }
        },
        {   "from": [ 8, 0, 0.8 ],
            "to": [ 8, 16, 15.2 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45, "rescale": true },
            "shade": false,
            "faces": {
                "west": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross" },
                "east": { "uv": [ 0, 0, 16, 16 ], "texture": "#cross" }
            }
        }
    ]
}
```
