### ISSUE TITLE
Question: GT Nuclear Reactor

### ISSUE THREAD

**Issue by Ethryan** [GregTechCE/GregTech#246]
Now that IndustrialCraft 2 isn't required for this mod, are you going to implement a GregTech native nuclear reactor?

Or will we still need to download and install IC2 to have one.

**Comment by Exidex** [comment]
This is on TODO list

**Comment by Ethryan** [comment]
Ah, thanks for the info

**Comment by KrisBigK** [comment]
Well, since it is impossible to convert IC2 EU to GT EU, IC2 reactors won't help at all.

**Comment by MineTech123** [comment]
Kris it’s not impossible it is possible but you need the ceu to convert from gteu to Fe and other power converters to convert from Fe to eu

**Comment by SergeyAn70** [comment]
Daily check the updates. I really want to build a nuclear reactor and a system to control its operation. The harder it is the more interesting....

**Comment by Agrax** [comment]
> 
> 
> Daily check the updates. I really want to build a nuclear reactor and a system to control its operation. The harder it is the more interesting....

Have you already talked w/ Arch abt it? Whether he'll accept a nuclear reactor of a given design? Unless you're making an addon

**Comment by huneau** [comment]
Hello, 
I planned to implement all kinds of existing reactors in the world inside Shadow-of-Greg, but It's probably a good idea to add it here?

**Comment by Shattered2909** [comment]
Maybe you wanna talk to the Nukepowered Utils dev?

**Comment by huneau** [comment]
who is active ? shadow-of-greg or Nukepowered-Utils ?

**Comment by Shattered2909** [comment]
Nukepowered Utils is a port of Shadows/Gregic Additions with more features, would be nice to have all the content in 1 Addon.

**Comment by Agrax** [comment]
> Nukepowered Utils is a port of Shadows/Gregic Additions with more features, would be nice to have all the content in 1 Addon.

If i were huneau, i’d talk with Archengius and come up w/ an innovative nuclear system that could be implemented in the base GTCE, as Archie WANTS fusion/fission in his mod really bad, but:
A) he doesn’t like the IC2 solution
B) doesn’t have the time/manpower to implement an innovative, never-seen idea

If you know how to approach the Russian, he’s both helpful and reasonable. I would suggest huneau so that he approaches the PR in multiple stages:

A) describing your nuclear system to Arch in a few phrases. He’d mostly agree and request some changes/features
B) making a test PR, because Arch usually doesn’t like spaghetti code (even if his code isn’t always 100% foolproof)
C) waiting for the PR to get accepted/rejected
D) pushing the real code when you know if Arch likes your coding technique ;)

**Comment by TheDarkDnKTv** [comment]
> Nukepowered Utils is a port of Shadows/Gregic Additions with more features, would be nice to have all the content in 1 Addon.

I already have plans about realistic reactors, but is is complicated to make it. There is needed a lot of time, experience and code.

**Comment by DStrand1** [comment]
Closing this as stale and duplicate, new discussion thread here #1426
