### ISSUE TITLE
[Suggestion] Ability to disable materials added by default

### ISSUE THREAD

**Issue by Habeeb-M** [GregTechCE/GregTech#252]

**Comment by Rongmario** [comment]
Can you give some examples? Because large amounts or if all materials are required in progression or recipes in vanilla Gregtech?

**Comment by Habeeb-M** [comment]
In my pack I don't want all of the materials, and the machines will have custom recipes.

**Comment by CelestialPhoenix** [comment]
Some tool types are fairly useless due to low durability compared to the tech needed to make said materials. 
Why would anyone make a Kanthal pickaxe?

**Comment by Archengius** [comment]
no, ability to remove materials will not be provided. you can add new items for existing materials, trough

**Comment by Dream-Master** [comment]
@Habeeb-M i guess you the guy stole my gtnh pack text and use it for you own. Now you removed it after my complains. Better make an own pack with own ideas and not copy things. And about this issue if you don't know how to remove stuff to customize your pack better go and play a pack instead of developing one :/

**Comment by Habeeb-M** [comment]
Excuse me? If I removed it after you asked why do you care any more? It's not like I've advertised my pack or even put that much work into it yet. Ideas are ideas. I may magpie some, who cares, but it doesn't say anywhere I can't use ideas. And I'm asking the developers to add a feature to remove it, and it's not very nice for an established pack maker to tell newbies to fuck off.
