### ISSUE TITLE
Corrupted Machines After Updating

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#303]
So, after updating the server to the latest version, some machines have become corrupted, i.e. they've become invisible and upon breaking them people get the following crash: https://pastebin.com/NKzQAr4c However, they can still open the GUIs of the machines.
 Even after breaking it with a block breaker, placing something else there and replacing it, the newly-placed machine has the exact same issue.
 However, breaking them, restarting the server and replacing them fixes it, but again, breaking them is annoying.

**Comment by gerb82** [comment]
ok. so that was what we thought upon updating. here is what we know now, which is A LOT more detailed, after lots of experimentation:
the issue appears when the first set of "cracks" is supposed to be rendered on the machine.
when the cracks are supposed to appear, the game attempts to get the light value of the machine in order to figure out how to render them.
when that happens, it calls the .getMetaTileEntity method in regtech.api.block.machines.BlockMachine
on line 114, the tile entity gotten from the position that was given to the function, is casted into a MetaTileEntityHolder.
the problem is, that for some reason, the tile entity that it tries to cast will be that of a nearby tile entity (one touching either one of the sides), or at least, it will also try to cast that. so as long as two gt machines are near just each-other, they will not cause a problem, as they can cast each-other, so they work well when they break. the problem is when there is a non-machine tile entity nearby (in the crash-log above, a thermal dynamics fluid duct, but it can be a gt pipe, a cable, anything (even a chest)).
i can't honestly say what is causing that issue, but we managed to replicate it on an instance with just gregtech, and no other content mod (not counting dependencies if there are any, i don't remember that as someone else set up that test instance).
all i know is that line 114 in regtech.api.block.machines.BlockMachine, gets the wrong tile-entity (or at least, it also gets a wrong one) when it does blockAccess.getTileEntity(pos), so the casting fails

**Comment by Archengius** [comment]
because mc rendering is fucking retarded and it calls block's getLightValue for it's neighbour blocks. Added additional check to make it suck dick.
