### ISSUE TITLE
GT Chest dont support Inventory Tweaks

### ISSUE THREAD

**Issue by Black0305** [GregTechCE/GregTech#348]
You cant use the auto-sorting in the GT chests.

**Comment by Rongmario** [comment]
Also Inventory Sorter.

**Comment by Archengius** [comment]
no idea how these mods work, report to them as required.

**Comment by OvermindDL1** [comment]
For note, a mod can either tell InvTweaks that such-n-such container supports it (I.E. a normal inventory and not some machine or so), or the user can tell InvTweaks themselves if it is a simple-enough inventory (otherwise the mod, like GTCE, has to tell it itself, like for example if only certain slots are sortable or so or it is a non-vanilla standard size).  It's all in the documentation:  https://inventory-tweaks.readthedocs.io/en/latest/#adding-configured-compatibility-info

**Comment by EmosewaPixel** [comment]
Thing is the chests count as machines.

**Comment by OvermindDL1** [comment]
> Thing is the chests count as machines.

As long as they have some kind of unique name for their TE then the use could potentially add the compat themselves, otherwise (and for ease of use), GTCE should still handle it itself.

**Comment by OvermindDL1** [comment]
> All information it needs can be easily retrieved from container instance.

Unless things have changed since I left Forge, it doesn't.  The IInventory interface has no concept of possible grouping, allowed sorting, changing, and so forth of slots.  A quick look at the current incarnation of IInventory and the Forge extensions there-of still show that it does not have the ability to give such information.

Another API is not necessary to depend on that either, a simple single reflective call in to it if it exists (else do nothing) to tell it about the required type information is all that is necessary.  No hard dependency is required.

**Comment by Archengius** [comment]
IInventory is ancient shit that is replaced with IItemHandler in modern versions of MC
And since InventoryTweaks sorts containers, it can just use Container instance to check all slots needed.
I would accept such special compatibility with dumb mods only if they will use Forge IMC.

**Comment by OvermindDL1** [comment]
> And since InventoryTweaks sorts containers, it can just use Container instance to check all slots needed.

Except that does not give information about what should be allowed to be sorted where and in what slots.

> I would accept such special compatibility with dumb mods only if they will use Forge IMC.

Because string messages really tells something how dynamic sorting can be done sure (remember that invtweaks even support resizable inventories, inventories with different even dynamicly changing grouping and only sorting within those if the cursor is in such a group, etc... etc... etc...).

**Comment by RobertLSnead** [comment]
It would still be nice to see this feature added.
I'll stick to iron chests for now!
-Thanks
