### ISSUE TITLE
TOP + GTCE + Server = Un-translated name showing in detailed inventory.

### ISSUE THREAD

**Issue by rallias** [GregTechCE/GregTech#360]
https://github.com/GregTechCE/GregTech/blob/e32b07707ba5b41ede5818e5fe3054ba964479a1/src/main/java/gregtech/api/items/materialitem/MaterialMetaItem.java#L95

This function is called by The One Probe at https://github.com/McJtyMods/TheOneProbe/blob/1.12/src/main/java/mcjty/theoneprobe/apiimpl/providers/ChestInfoTools.java#L95 on server-side. However, being that it's not available server-side for GregTech, this is hindering the ability to view item name on the server.

Attached item is Magnetite Dust.

![11rxtbt](https://user-images.githubusercontent.com/1843506/46577306-a33add00-c9a9-11e8-89b3-5e5ae3b831c6.png)

**Comment by Archengius** [comment]
TOP issue. Language-dependent functions were never intended to be called on server side.

**Comment by rallias** [comment]
Gregtech issue. You're overriding a non-@SideOnly function with a @SideOnly parameter, causing breakage in cross-mod interaction.

**Comment by Archengius** [comment]
This function uses I18n, which is clientside-only class, and replaces old
deprecated I18n that is removed in 1.13.
As i said earlier, don't except localization functions to work properly on
server side.
Try to switch language to non-english and check item name in TOP - you will
be disappointed, it will remain english instead of getting translates.
If function isn't marked as clientside-only in MC, it doesn't mean it will
actually work properly on serverside, especially if it is related to
localization.

пн, 8 окт. 2018 г., 1:10 Andrew Pietila <notifications@github.com>:
