### ISSUE TITLE
[Suggestion] Only re-lookup machine recipes when items/fluids change.

### ISSUE THREAD

**Issue by omsfuk** [GregTechCE/GregTech#468]
I took a look at your code and found that most of the code is elegant but there are also some questions. For example the recipe lookup uses a linear lookup method. When the recipe table is large, such as an assembler which contains 2000+ recipes and cause a lot of overhead (my test also proves this, Especially when there are items inside the assembly machine). So why not use binary search, just need to sort the recipe, the cost is only a little more loading overhead.

This is just my opinion or suggestion. please indicate if there is any error. 
Anyway, I hope this mod will be better.
Sorry for my poor english : )
as a GregTechCE fan

**Comment by Archengius** [comment]
You cannot sort recipe by inputs, because inputs are not ItemStack but just Predicate<ItemStack> with any complex or simple logic behind it. RecipeMap has no knowledge of possible combinations and values of these predicates, so the only thing it can do for searching recipes is linear lookup with matching every recipe's input predicates.
Taking in account all machines cache their recipe for future usage, i don't really see the problem here. Looping through 2k elements is pretty fast too.
However, PRs and ideas how it can be optimized while keeping things as dynamic as they are now, are welcome.

**Comment by omsfuk** [comment]
Thank you for your reply.
* But this still has problems. The cache only works when the recipe exists. I know once the machine is running, there will be no such problems.But what if the recipe doesn't exist as well as the machine is NOT Running?
If the machine is not running, it will try to check the inventory at regular intervals, thus causing the need to search the recipes frequently, and the cache will not hit.

* Due to the automation of Machine Hull, I need to keep a configuration circuit in the assembler。When I use LagGoggle to watch the TileEntiy which take more tick time, I found the assembler was the most.
* You can reproduce it by following the steps below.
	* Place an assembly machine
	* Place a configuration circuit in the assembler  with any number
	* Place a assembler with empty inventory
	* Place a chemical reactor
	* Open LagGoggle to get the results
	* Compree the result

(And I don't think this was a mistake by LagGoggle)
you will found the assember takes up a lot of tick time.
![2018-12-27_19 28 01](https://user-images.githubusercontent.com/26737684/50478998-30248e00-0a0f-11e9-9b4a-0ced698c9abf.png)
(Please ignore the Chinese : )

* If you agree with what I said above, let's start the next topic : )
So why not try to split the recipes , for each possible list of a separate recipe, ranther than "Predicate"?
I know this may lead to a large increase in synthetic tables, but may be this problem can be solved by the OreDict.

In addition, the chemical reactor is also lag even if its inventory is empty. I have not figured out it.
In my test, the assembler takes 600+ us and the chemical reactor takes 64us, but most other machine take 1~5us

(Maybe you except a PR, but I'm too lazy : P)

**Comment by Archengius** [comment]
I will not split recipes, they will remain dynamic. Some recipes can have thousands of variants due to dependence on item NBT data. 
There is a problem with caching non-existing recipes, yeah. Actually, they should be re-lookup only when inventory contents is changed. Ideally, i will do as soon as i will have time for the mod.

**Comment by omsfuk** [comment]
That's great! 
I didn't know forge supplied the InventoryChangesEvent (Or maybe you manually check). Without changing the current recipe system, it's a pretty good idea to search for recipes only when inventory changes.
This mod will become more tps friendly, which is so exciting, then I can enter the end-game happily without worriing about TPS :)
This mod was the most tps friendly mod I have seen
Thank you and your team again for your efforts in this mod!
