### ISSUE TITLE
Add Disassembler to disassemble tools instead of magic lunch boxes.

### ISSUE THREAD

**Issue by Archengius** [GregTechCE/GregTech#470]

**Comment by WazWaz** [comment]
Or just allow the tool's tips to be replaced, since that's where the "durability" is coming from. That's how you'd repair a real-world chainsaw, not disassemble the entire machine, accidentally dropping a few pieces on the floor in the process (but if you don't drop the tip, it magically repairs itself....).

**Comment by Archengius** [comment]
Replaced by #605
