### ISSUE TITLE
[Suggestion] Only try to "extract" energy when machine need it

### ISSUE THREAD

**Issue by omsfuk** [GregTechCE/GregTech#529]
After fix #468 , the laggest machine in GTCE become Transformer or BatterBuffer with a lot of "route node" (to be exactly, RoutePath)

In the following example, a transformer linked to 8 not working machine. Transformer takeup 18us, but machine just 0us or 1us
![2019-01-21_01 42 02](https://user-images.githubusercontent.com/26737684/51442983-e4b78400-1d1d-11e9-99c6-33af303d761f.png)

passive energy transmission is better than active energy transmission.
That means, "working" machine try to extract energy on their own initiative, other than Transformer or BatteryBuffer active push energy to machines.

Because in mose cases, most machine was not working, only a few are working. Only working machine need energy. In many cases, transformers don't need to work at all.

In my world, machine not working take up about 1 us, but a transformer take up about 20us, even no machine consume energy.

From my last failed pull request #519 , I know my changes may not suit your taste, so I will not try to submit my code as well as pull request anymore. I think it would be better for you to solve this problem.

Again, sorry for my bad english : )
Anyway, I just want GTCE to be better & TPS friendly

**Comment by Archengius** [comment]
Pulling energy from network is not how things should work, and iterating 10 routes is not that heavy.
Nope.

**Comment by omsfuk** [comment]
One moment please, but it is really a problem. my BatteryBuffer linked with more than 50 tranformer takes up about 200us. This is totally an unnecessary overhead. Passive energy transfer does work.
Thank you for your reply

**Comment by Archengius** [comment]
Passive energy transfer causes even more bugs in current tricky design in e-net and introduces more difficulties.
Don't link battery buffer to 50 transformers, also.

**Comment by omsfuk** [comment]
Oh, please forgive my ignorance, thank you :)

**Comment by GregTecher** [comment]
I came up with the idea of expanding the machine's energy buffer and changing energy transmission interval, for example, 0.5s
For example, the IV transformer, which was originally transmitted per Tick (4A x 8192V) eu, 
is now changed to every 10Tick transmission (10 x 4A x 8192V) eu, which may cause some minor problems, 
but I think that these problems can be ignored compared to the benefits it brings.

PS: I have to think about this again, because half of my TPS is now being taken away by the transformer. 
I have about 200 transformers in the whole base. Even if each transformer only takes 4us, it will be a big one. 
The overhead, especially in the server. 

Or you can provide an option to choose whether to use this energy method to reduce the load. This is simple, 
just increase the energy buffer and change the energy transfer size and interval.

For a more TPS friendly GTCE!
Thank you

**Comment by Archengius** [comment]
i'm not going to change transmission rate
i don't see benefits it brings
i'm not going to provide any options
GTCE is already tps friendly enough
have a nice day

**Comment by GregTecher** [comment]
Well, still thank you.

**Comment by omsfuk** [comment]
PS:
* I implemented it and tested it. by changing energy 
transfer rate to 16ticks, my server TPS changed from 4.5ms/50ms to 2.2ms/50ms and the whole GregTech machines took from 4000+us to 1200+us. 
* Of course, I don't expect you to adopt my ideas : ). After all, I also feel that it is not so elegant.I just hope that this may give you a little inspiration.
If you are interested, you can take a look [it](https://github.com/GregTecher/GregTech). a littte change, just modify the `acceptEnergyFromNetwork` method, make it receive/emit energy by 16x

Sorry to bother you
(I didn't release it, if it damages your rights, I will delete it immediately: )

**Comment by Rongmario** [comment]
@omsfuk 可以傳給我試試? 我有做一個Fork
