### ISSUE TITLE
I've received Reports that someone tries to steal your Project.

### ISSUE THREAD

**Issue by GregoriusT** [GregTechCE/GregTech#7]
Quite a few people told me on my IRC Channel, aswell as me witnessing some parts myself, that there is a huge Problem in GTCE and it is very likely that this Project will be stolen in the near future, and I do not want to let that happen.

I see it as a serious Issue that a Project that could turn out as a nice thing for the community, starts to get taken over by someone, who obviously doesn't care about it and only wants to end up making money for less than nothing in return. I'm talking about Alkalus.

There is several things that are alarming about him, which will result in this Project breaking apart soon if he isn't stopped in time.

He already took over the "Organisation" of this Project, and claims to be the "Project Manager" on his Patreon. The way he works on his Projects is very dangerous for any Project, ignoring Bugs because people didn't vote for them to be fixed, creating Features that don't even do what they were originally made to do in the first place, ignoring and shutting up Testers who are supposed to report Bugs, using Items and Blocks without using Metadata at all, because "it doesn't matter anyways" (in his 1.7.10 Projects, where there is a hard ID Limit for all Mods), and then expecting from everyone to admire his "effort" just because he is Homeless and should actually do other stuff instead of modding, regardless of the result of said effort is being worse than not doing anything at all in the first place.

I talked with Bloody about it and Alkalus seemed to try to do that in GT5U aswell and that he considered banning Alkalus because of his behaviour. So be warned that he is already trying that with this Project aswell. He is essentially doing the same stuff that Lex did when he took over Forge, slowly gaining power over more and more "seemingly irrelevant" parts of the Project, including the Web Domains, until he took it over entirely by force.

You need to be very careful when doing any sort of Community Project, because that can happen to anyone. Always be wary when someone makes a suggestion that gives themselves more power, even though they don't actually do anything useful for the Project. It can end very badly.

Originally I did not want to show up over here and say all of this, but my only contact to all of you was reluctant to relay my messages, due to thinking that you will ignore me anyways, so I had to show up myself.

Be very careful about him and dont fall for his tricks. I would kick people like him out of the Team as soon as possible if I was responsible, but I cant tell you what to do. And "fork and run" doesn't work once the Project has reached a certain size, especially if there is a website domain or anything under the control of the wrong person.

I still hope for this Project to become something that is not as broken as GT5U, or as incomplete as GT6 is right now.

Best Regards
~ Gregorius Techneticies

P.S. I hope Alkalus doesn't have the power to delete this issue, or to hide it somehow.

**Comment by draknyte1** [comment]
Afternoon Greg,
While I do have the power to do so, I won't.

I have no interest in controlling the direction of either project, at all.
I simply give my opinions.

My role as "Project Manager" is self claimed, wholly unofficial and only covers what I do outside of Actual coding with Gregtech. This extends to reviewing other contributions, doing writeups and trying to keep the other guys in the team to some standard (See project guidelines in Contributing.md for gt5u).

I've never made a patreon until recently for exactly this reason, but where am I wrong let people fund me for my efforts? I haven't claimed anything that isn't true across my patreon posts or discord either.

Your opinion is based on bias judgement from friends of yours, so it's not really a fair defence on my behalf no matter how you paint it. While I won't mention who, for their own privacy, It's not like I mentioned these things to everyone. My Content vote was simply to gather a rough idea of what on my to-do list is of interest to the community. Not as an actual priorities list that I'd engage in strictly, thinking this is/was the case is just stupid.

Anyway, end of the day, I hold no actual control anyway and don't pretend as much.
Each project has their respective owner and I can respect that, which is why for example, all GT5u contributions, we still leave everything to @Blood-Asp for final review and merge. We've had our differences over the past 24 months, but I was pretty sure we got past that awhile ago. But please, Correct me if I'm wrong.

I can't really control the code either, because for GTCE I haven't contributed any, nor do I plan to in the relatively close future. This hurts me Greg, because it was an issue we didn't need to bring up in public when a small few people feel personally afflicted.
