### ISSUE TITLE
Glowstone inconsistency

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCE/GregTech#72]
There seem to be many recipes related to glowstone, some consider a block to be 9 dust, others consider it to be 4. Often enough, just both. I recommend going with 4 dust because most other mods do as well and removing the 9:1 crap.

**Comment by Archengius** [comment]
there is no "many" recipe. Give actual recipes screens.

**Comment by EmosewaPixel** [comment]
In the pulverizor (since it's 36 small dust, it's 9 regular dust)
![image](https://user-images.githubusercontent.com/25333164/40990496-4d4f9016-68f1-11e8-8de1-6cc80153343a.png)
And the cutting saw has 2 variants of recipes (3 that give 4 and 3 that give 9 plates)
![image](https://user-images.githubusercontent.com/25333164/40990531-6f37b154-68f1-11e8-8fcc-ba66a08227e5.png)
![image](https://user-images.githubusercontent.com/25333164/40990536-724cb4d4-68f1-11e8-84d8-d3964a08dfe5.png)
 I'm pretty sure this issue occurs because of the way recipes are generated. Glowstone should be blacklisted.

**Comment by Archengius** [comment]
fixed
