### ISSUE TITLE
Pumps no longer work as infinite source of water

### ISSUE THREAD

**Issue by jnaset** [GregTechCE/GregTech#740]
Not sure if this change was intended or was a side effect of another change.

Previously, a pump positioned over a pool of water would pump water from the pool indefinitely.  When the pack I was playing (Gregblock) updated from 2.2.0 to 2.2.1, the pump behavior changed and it now attempts to pump each water source block once only before it begins seeking downward for more fluids (in my case there are none, so the pump stops working).

This change in behavior prevents the pump from being an infinite source of water for EU.
(As an aside, if the pump is intended to continue being an infinite source of water, it would reduce lag somewhat if it didn't remove the water source blocks, which regenerate a few ticks later anyway)

**Comment by Archengius** [comment]
neither will happen, change inteded

**Comment by jnaset** [comment]
With this change, then, GTCE becomes dependent on additional mods to supply water for machines like the ore washer or electrolyzer.

**Comment by sinopike** [comment]
there are ways to update water constantly to fill the gaps

**Comment by wu452148993** [comment]
A Temporary Solution ----- https://github.com/EmosewaPixel/GregBlock/issues/177#issuecomment-528169616

**Comment by Houndie** [comment]
While I don't mind this change, this feels like something that should at least wait until a 2.3 instead of 2.2.1.  I was hoping to update to 2.2.1 to fix some bugged recipies, but I find that now I have to make massive layout changes to my base before updating.

(I don't have a problem with the change to finite water, just the version numbering...it would be nice to have a bug fix release that only fixes bugs instead of changing gameplay)

**Comment by Glease** [comment]
@Houndie GregBlock is abandoned and no longer maintained. Plus, this is not the repo for gregblock anyway.

**Comment by Houndie** [comment]
TIL, and wow yup you're right.  I followed a link here from the gregblock repo, and didn't realize that I changed repos.

Sorry for the confusion :-P
