### ISSUE TITLE
Bronze/Steel Chests aren't real chests

### ISSUE THREAD

**Issue by ZeekDaGeek** [GregTechCE/GregTech#761]
Edit: Didn't mean to hit submit immediately, sorry.

The way the chests are currently implemented even vanilla short cuts like holding a stack of items and double clicking on an existing stack won't put all of the items in properly.

MouseTweaks scrolling will not work properly,
InventoryTweaks / Quark sorting doesn't work properly.

For what ever reason it seems that the way the chest is created doesn't seem to conform to normal inventory creation methods that other mods can interact with.

**Comment by Archengius** [comment]
what do you mean

**Comment by ZeekDaGeek** [comment]
Hi, panicing, didn't mean to hit submit so soon.

**Comment by ZeekDaGeek** [comment]
Sorry about that, hit enter instead of hitting tab and submitted, the issue has been updated.

**Comment by Archengius** [comment]
MouseTweaks scrolling will not work properly => MouseTweaks is borked when working with mod inventories using IItemHandler in general and it's not something i can fix on my side.
InventoryTweaks / Quark sorting doesn't work properly => Chests have huge Sort button in the top left corner, sorting of these mods doesn't work properly because of the same reason - they can't handle IItemHandler inventories properly in general and their inventory handling is outdated.
Didn't notice anything in vanilla GUI control not working, want to give an example?

**Comment by ZeekDaGeek** [comment]
Other features that don't work:
Quark's Deposit to nearby chests button.

It doesn't matter that the chests have a sort button, the example is intended as an example that no mods implementations of things that work on inventories work on GregTech Community Chests, which is problematic because it means creating specific cases for them.

Example of Vanilla's move every item short cut:

![ctqQJ](https://user-images.githubusercontent.com/1709288/56457484-ce2ec200-6338-11e9-8e8b-d4ddf4020d8b.gif)

Take an item in hand, hover over another item and double click.

**Comment by Archengius** [comment]
it doesn't create specific cases, only reason these mods work for IronChest chests are because IronChest is outdated and uses IInventory which is deprecated since the beginning on 1.12.2 development. If these mods can't handle IItemHandlers properly, that's not my problem, but theirs. 

vanilla dragging is fixed in dev, yet thanks for reporting it again.

**Comment by yrsegal** [comment]
IInventory is actually not the reason those work, FYI. For some reason, Quark checks the *registry name* of the tile entity, and looks for the word "chest" in it.

I'm discussing solutions with Vazkii.

**Comment by Archengius** [comment]
IInventory is exactly the reason why InventoryTweaks/InventorySorter doesn't work, no idea about MouseTweaks or Quark.

**Comment by yrsegal** [comment]
Fair enough.
