### ISSUE TITLE
Input hatch cant be emptied/cleared without a break and replace

### ISSUE THREAD

**Issue by daddy77gaming** [GregTechCE/GregTech#793]
put in a drum full of unstable mana in the EBF, did my crafts then wanted to take the remaining out. Couldnt not click with a drum,cell,bucket or anything to do so.

Then after a bit of searching tried with a plunger as it states sneak use on input hatch. Also didnt work only took durability on the plunger ( while plunger does work on machines, and saw a couple weeks ago plunger was fixed to take out less then a bucket worth as well )

**Comment by Archengius** [comment]
you cannot take fluids out of input hatches

**Comment by daddy77gaming** [comment]
Well all fine if that it is how it's intended. It would be nice to have tooltip on the plunger corrected then.

**Comment by desagas** [comment]
I know this is closed, but it does not make sense to have this be the only component that can not be removed from in the entire mod. All other input devices and machines can have their input contents removed, including buses, outputs, single machines, tanks, etc. While I know this is GTCE, in GT5, the wiki explains that you could remove via tanks and pipes.

**Comment by ashawkey** [comment]
Also hope liquid should be able to take out from input hatch too. Because of this feature, I have to wrench and replace the input hatch to clear the remaining liquid inside it . Since all the other machines' input liquid can be taken out by tanks, I think it will be consistent to allow input hatch to take out liquid too.

**Comment by Exaxxion** [comment]
This limitation is incredibly annoying and I hope you would reconsider. I can't think of any other mod that arbitrarily prevents you from emptying a fluid container once filled.

At current all you can do is void the contents, figure out LCMs of all your recipe fluid quantities so you can completely clear the input hatch (crafting way more times than you probably want to), or NBTEdit / otherwise cheat to get the fluid back which breaks automation. It wouldn't be an issue if recipes used whole buckets, but we have to deal with the weirdness of things like the 144 mB / ingot tradition.

**Comment by Agrax** [comment]
What’s the issue tho? Just use a fluid extractor feeding the hatch and you’re good when it comes to things like 144mB (which equals to one whole ingot)

**Comment by desagas** [comment]
You can not extract, period.

Denver Leman

On Sep 2, 2019, at 1:18 PM, Agrax <notifications@github.com<mailto:notifications@github.com>> wrote:


What’s the issue tho? Just use a fluid extractor feeding the hatch and you’re good when it comes to things like 144mB (which equals to one whole ingot)

**Comment by Exaxxion** [comment]
> What’s the issue tho? Just use a fluid extractor feeding the hatch and you’re good when it comes to things like 144mB (which equals to one whole ingot)

It's not quite that simple.

First, not all fluids are sourced from melted metals. Plenty are gases. I might be mistaken but I don't think I can make for example helium ingots and nuggets.

Second, if you already have a large stock of the fluid in a container (let's say a higher-end GT drum full) how do you extract precise fractional quantities from it into a hatch without first having to cast, measure, and extract them again? If you can, how do you prevent it from continuing to dispense the fluids when the container still has fluid in it but you don't want more going into the hatch?

Third, recipes often require fluids in hundredths or quarters of a bucket. Getting the exact LCM for those may require crafting hundreds of items instead of a couple that you actually want.

**Comment by Agrax** [comment]
Can’t AE or other mod handle that? Otherwise make a suggestion so that the fluid filter cover, when put into a pump, allows the pump to store only a certain amount of a given fluid: just like the robotoc arm does for items

**Comment by Exaxxion** [comment]
No mods can extract fluid already in an input hatch. That's kind of the complaint.

However, assuming you're talking about getting it to the hatch in the first place, AE2 has basically zero support for fluid crafting aside from storage and bulk I/O. You can't put fluids in processing patterns, you just pretend it's already there. In Omnifactory for example we just bite the bullet and dedicate a machine or multiblock to every distinct fluid combination, which sucks.

As to the pump suggestion, I thought about that too. I very much like the idea and would be happy to open a suggestion ticket if that's the route you want to go.

I had considered a few solutions including robot arm-like settings on pumps and adding the drain GUI and logic from fluid output hatches to the input hatch so you could bucket out excess. I reviewed the code related to hatches, pumps, robot arms, and conveyors but couldn't see a route to implementation of any of the solutions without significant decoupling and I don't trust that I'd be aware of all the possible side effects. I was surprised for example that both types of hatches are the same class with functionality split up with conditionals, and that robot arms are a subclass of conveyors.
