### ISSUE TITLE
[Old Feature] Allow transfer (fuild item) covers to both input and output

### ISSUE THREAD

**Issue by Rosethorns** [GregTechCE/GregTech#874]
In GT5 conveyers/arms/pumps e.t.c could input and output from the same cover.
With the new configuration menu they can only export OR import but not both. This heavily restricts how useful they once were.

**Comment by Archengius** [comment]
..for using EIO pipes.

**Comment by Rosethorns** [comment]
what?

**Comment by Archengius** [comment]
Only usability of such mode is pipes that allow both input and output from one side. Currently, only pipes behaving like that are EnderIO pipes. Making feature specifically for one mod is not what i want.

**Comment by Rosethorns** [comment]
Uh no. input AND output was used all the time for GT5U from one machine next to another. I'm highly confused how you believe it is only useful for one mod considering it was a /base/ function of covers in the original GT5 version

**Comment by A-UNDERSCORE-D** [comment]
>..for using EIO pipes.
Thermal Dynamics piles can do this too. Using retrievers and regular servos to push and pull from the same face.

**Comment by MidoriKami** [comment]
Another valid use case is Applied Energistics Fluid Interfaces. There are 6 fluids that can either import and export from the AE system. Take for example the recipe for Ethylene, the first slot in the fluid interface would be Ethanol, the second slot would be Sulfuric Acid, and then the remaining 4 slots would be empty allowing input into the AE system.

This allows all fluids to be managed from one side of the machine rather than requiring multiple sides.
