### ISSUE TITLE
Machine Controller loses settings on server restart

### ISSUE THREAD

**Issue by predakanga** [GregTechCE/GregTech#905]
Machine Controller covers reset from inverted to normal mode on each server restart (possibly chunk unload as well).

Seems to be caused by a simple typo, PR to follow.

**Comment by gigglingNerd** [comment]
Hi. I am having this exact problem with GTCE in Omnifactory. Is it possible that I'm playing with a version of GTCE from before this was fixed? My version is GTCE version 1.8.4.419 btw.

**Comment by Exaxxion** [comment]
Hello, I'm the lead maintainer of Omnifactory. GTCE 1.8.4 is from shortly before this issue was fixed. If you're currently playing on 1.2.2, I would recommend updating to play on the development snapshots, which have been updated to use the current version of GTCE. We have a guide for that here: [Playing On Dev](https://github.com/OmnifactoryDevs/OmnifactoryGuides/blob/latest/guides/PlayingOnDev.md).

**Comment by gigglingNerd** [comment]
Okay. Thank you, Exaxxion. Great modpack btw.
