### ISSUE TITLE
JEI recipes not working

### ISSUE THREAD

**Issue by oliverking2** [GregTechCE/GregTech#951]
The recipes for using the machines (e.g. using the macerators) no longer show up in JEI using the newest version of GTCE for 1.8.4 and 1.8.5

**Comment by kobliznik** [comment]
Remove Shadows of Greg/GreggicAdditions..

**Comment by Guswut** [comment]
To note, I wasn't able to confirm this using just GregTech Community Edition and Shadows of Greg (in the FTB Interactions pack) which I was hoping to do to avoid loading my full pack to test, but I was able to resolve the underlying issue (JEI recipes not working) by installing the latest version of Shadows of Greg (https://www.curseforge.com/minecraft/mc-mods/shadows-of-greg/files/2774616).

This also retained the fix to lumber axes not working which is why I originally manually upgraded the GregTech Community Edition version, so it is the best of both worlds!

I'm commenting just in case anyone else ends up looking for a solution to this issue in the future, good luck, and thanks.

**Comment by kobliznik** [comment]
Ok, you updated, but this issue was broken for weeks until SoG author updated it. It is too long to risk using this mod in modpack on public MP server (for me). So I removed this mod to avoid this bugs.

**Comment by Archengius** [comment]
I suggest not replying on SoG because it's dead in fact

**Comment by Blood-Asp** [comment]
The latest updates for SoG where my PRs. I plan to keep it alive as long MC 1.12 is still active and not moved mostly to 1.14+
