### ISSUE TITLE
Ore/Oil and Machines

### ISSUE THREAD

**Issue by NIKOL-CRASH** [GregTechCE/GregTech#975]
Oil generation as in Buildcraft? NO,No,no Better as in the original gregtech! Say version 5.09
 Generation in the chunk
Ore ore ore,    How do I dig it all up? Use Advanced miner IC2?
 Who can’t even take EU energy from gregtech. As well Not Support Applied Energistics 2 cable(no connect).
No "IV" Machines and UP (LuV,ZPM,UV)
release? exactly release?
I don’t understand how it can be in the release
That is not, This is not.

**Comment by Archengius** [comment]
Oil generation is fine, and it's better than randomly having imaginary oil in chunks somewhere behind the bedrock.

 You can deep huge amounts of ore already with jackhammer, which supports 4 different modes of mining, one of whoose is 3x3. Miner is still coming, but you can perfectly satisfy your ore requests now even without it.

While usage of IC2 is discouraged, you can use CEU add-on to convert energy to IC2 EU and RF. Decision not to support GTEU is purely on AE2 Devs, but still, you can use converters from CEU.

There are no IV+ machines simply because they make no sense to use, their EU efficiency will be too low and their cost is astonishing. New endgame is being worked on, through.

Also, nobody forces you to understand that, you don't need to understand fact to see it happen :)

**Comment by Archengius** [comment]
Thank you for feedback anyway
:)
